import urllib.request
import urllib.error
import urllib.parse
import json
import html as html_lib
import re
import socket
import sys
from datetime import datetime
import os
import shutil
import time

API_URL = "https://firmware-api.gl-inet.com/cloud-api/model/info"
# Public base URL of the deployed site (absolute links in API files, device pages and link previews)
SITE_URL = "https://firmware.gl-i.net"
SITE_NAME = "GL.iNet Firmware Overview"
# Preview image for links shared on social media / forums (Open Graph, Twitter Card)
OG_IMAGE_PATH = 'images/og-image.png'
OG_IMAGE_SIZE = (1200, 630)
THEME_COLOR = '#343a40'

# Per-model pages are generated at the site root (/<model>/index.html). Root entries
# that a model page must never overwrite:
RESERVED_ROOT_NAMES = {'api', 'images', 'cloudflare', '.git', '.github', '.claude'}
# Marker embedded in generated model pages so stale ones can be removed safely
DEVICE_PAGE_MARKER = '<!-- generated by generate_page.py (device page) -->'

# Preferred order of firmware stages; unknown stages follow alphabetically
STAGE_ORDER = ['RELEASE', 'BETA', 'SNAPSHOT', 'RC']

TYPE_ICONS = {
    'ROUTER': 'fa-wifi',
    'IOT': 'fa-broadcast-tower',
    'KVM': 'fa-server'
}

TYPE_NAMES = {
    'ROUTER': 'Routers',
    'IOT': 'IoT Devices',
    'KVM': 'KVM / Comet Series'
}

# Styles shared by the overview and the device pages
PAGE_STYLE = """
        body { background-color: #f8f9fa; padding-top: 20px; }
        .card { margin-bottom: 30px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border: none; }
        .card-header { background-color: #343a40; color: white; font-weight: bold; padding: 12px 20px; }
        .badge-stage { font-size: 0.8em; }
        .table-hover tbody tr:hover { background-color: #f1f1f1; }
        .fw-version { font-family: monospace; font-weight: bold; }
        .timestamp { font-size: 0.8rem; color: #6c757d; }
        .search-container { margin-bottom: 30px; }
        footer { margin-top: 50px; padding: 40px 0; text-align: center; color: #6c757d; font-size: 0.9rem; border-top: 1px solid #dee2e6; }

        /* Stage specific colors */
        .stage-RELEASE { color: #198754; }
        .stage-BETA { color: #0d6efd; }
        .stage-SNAPSHOT { color: #0dcaf0; }
        .stage-TESTING { color: #dc3545; }
        .stage-RC { color: #fd7e14; }

        .fallback-link { font-size: 0.75rem; font-family: monospace; color: #6c757d; }
        .fallback-link:hover { color: #0d6efd; }
        .model-type { font-size: 0.7rem; text-transform: uppercase; color: #adb5bd; letter-spacing: 1px; }
        .api-info { background: #e9ecef; border-radius: 8px; padding: 20px; margin-bottom: 30px; }
        code { background: #f1f3f5; padding: 2px 4px; border-radius: 4px; color: #d63384; }
        .section-title { margin-bottom: 15px; font-weight: bold; color: #495057; display: flex; align-items: center; }
        .section-title i { margin-right: 10px; }

        /* Device pages */
        .model-link { color: inherit; text-decoration: none; }
        .model-link:hover { text-decoration: underline; }
        .model-link .fa-link { font-size: 0.7em; opacity: 0.4; }
        .changelog-text { white-space: pre-wrap; word-break: break-word; font-size: 0.85rem; background: #f1f3f5; border-radius: 8px; padding: 15px; margin: 0; }
        details summary { cursor: pointer; }
        .share-bar .btn { padding: 0.15rem 0.55rem; font-size: 0.8rem; }
"""

# Copy-link / native share behaviour of the share bar (progressive enhancement:
# the network buttons are plain links and work without JavaScript).
SHARE_SCRIPT = """
<script>
    document.querySelectorAll('.share-bar').forEach(function(bar) {
        var url = bar.dataset.shareUrl, title = bar.dataset.shareTitle;
        var copy = bar.querySelector('.share-copy');
        var done = function() {
            var original = copy.innerHTML;
            copy.innerHTML = '<i class="fas fa-check me-1"></i>Copied!';
            setTimeout(function() { copy.innerHTML = original; }, 2000);
        };
        // Older browsers, or contexts where the async clipboard API is blocked:
        // select the link in a temporary field and use the legacy copy command.
        var legacyCopy = function() {
            var field = document.createElement('textarea');
            field.value = url;
            field.setAttribute('readonly', '');
            field.style.position = 'fixed';
            field.style.opacity = '0';
            document.body.appendChild(field);
            field.select();
            var ok = false;
            try { ok = document.execCommand('copy'); } catch (e) { ok = false; }
            document.body.removeChild(field);
            if (ok) { done(); } else { window.prompt('Copy this link:', url); }
        };
        copy.addEventListener('click', function() {
            if (navigator.clipboard && navigator.clipboard.writeText) {
                navigator.clipboard.writeText(url).then(done, legacyCopy);
            } else {
                legacyCopy();
            }
        });
        var native = bar.querySelector('.share-native');
        if (navigator.share) {
            native.classList.remove('d-none');
            native.addEventListener('click', function() {
                navigator.share({ title: title, url: url }).catch(function() {});
            });
        }
    });
</script>
"""

# Seconds a firmware download link gets to answer a single HEAD request. A
# healthy answer takes well under a second, so this is generous on purpose.
LINK_TIMEOUT = 8

# Transient failures (timeout, reset, 5xx, 429) are retried; a 404 is not.
LINK_ATTEMPTS = 3
LINK_BACKOFF = (1, 3)  # seconds to wait before attempt 2 and attempt 3

# Upper bound on the extra time retries may cost across one whole run, so a bad
# day upstream cannot turn a 90 second build into an hour of waiting. Once it is
# used up the remaining links get a single attempt each.
RETRY_BUDGET = 180
_retry_budget_left = RETRY_BUDGET

# When the newest build's download is unreachable, how many older builds to
# probe for one that still downloads. Those probes get a single attempt each so
# one broken model cannot eat the whole retry budget.
FALLBACK_CANDIDATES = 5

IS_GITHUB_ACTIONS = os.environ.get('GITHUB_ACTIONS') == 'true'

# Stream the build log instead of flushing it in one block at the end of the step.
try:
    sys.stdout.reconfigure(line_buffering=True)
except AttributeError:  # Python < 3.7
    pass

def log_progress(message):
    """Progress output: transient on a terminal, a real log line in CI."""
    if sys.stdout.isatty():
        print(message, end="\r")
    else:
        print(message)

def log_annotation(level, message):
    """Emit a GitHub Actions annotation so problems show up on the run page."""
    if IS_GITHUB_ACTIONS:
        # Annotations are single-line; encode newlines the way Actions expects.
        print(f"::{level}::{message.replace(chr(10), '%0A')}")

def attempt_link(url):
    """One HEAD request. Returns (ok, reason, retryable, duration).

    A 4xx answer is the server telling us the file is not there, so it is
    final. Timeouts, resets, 5xx and 429 are worth another try.
    """
    started = time.monotonic()
    try:
        req = urllib.request.Request(url, method='HEAD')
        req.add_header('User-Agent', 'Mozilla/5.0')
        with urllib.request.urlopen(req, timeout=LINK_TIMEOUT) as response:
            duration = time.monotonic() - started
            ok = response.status == 200
            return ok, f"HTTP {response.status}", not ok and response.status >= 500, duration
    except urllib.error.HTTPError as e:
        retryable = e.code == 429 or e.code >= 500
        return False, f"HTTP {e.code} {e.reason}", retryable, time.monotonic() - started
    except urllib.error.URLError as e:
        duration = time.monotonic() - started
        if isinstance(e.reason, (socket.timeout, TimeoutError)):
            return False, "timeout", True, duration
        return False, f"{type(e.reason).__name__}: {e.reason}", True, duration
    except (socket.timeout, TimeoutError):
        return False, "timeout", True, time.monotonic() - started
    except Exception as e:
        return False, f"{type(e).__name__}: {e}", True, time.monotonic() - started

def check_link(url, max_attempts=LINK_ATTEMPTS):
    """HEAD the URL, retrying transient failures within the global budget.

    Returns (ok, reason, attempts, duration). The reason explains the failure
    for the build log and the status page instead of collapsing it into a bool.
    """
    global _retry_budget_left

    if not url or url == "#":
        return False, "no download URL in API response", 0, 0.0

    total = 0.0
    reason = "not checked"
    for attempt in range(1, max_attempts + 1):
        if attempt > 1:
            if _retry_budget_left <= 0:
                return False, f"{reason}, no retry budget left", attempt - 1, round(total, 2)
            wait = LINK_BACKOFF[attempt - 2]
            time.sleep(wait)
            total += wait
            _retry_budget_left -= wait

        ok, reason, retryable, duration = attempt_link(url)
        total += duration
        if attempt > 1:
            _retry_budget_left -= duration
        if ok:
            return True, reason, attempt, round(total, 2)
        if not retryable:
            return False, reason, attempt, round(total, 2)

    return False, reason, max_attempts, round(total, 2)

def find_reachable_fallback(candidates):
    """Newest older build whose download still responds, or None.

    Used only when the current build's own download is unreachable, so that
    the overview can still offer something downloadable.
    """
    checked = 0
    for candidate in candidates[:FALLBACK_CANDIDATES]:
        link = entry_link(candidate)
        if not link:
            continue
        checked += 1
        ok, _reason, _attempts, _duration = check_link(link, max_attempts=1)
        if ok:
            return candidate, link, checked
    return None, '', checked

def extract_changelog(entry):
    """Extract changelog text from known API field variants."""
    changelog_keys = [
        'changelog', 'release_notes', 'release_note', 'notes',
        'description', 'change_log', 'whats_new', 'what_is_new'
    ]

    for key in changelog_keys:
        value = entry.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
        if isinstance(value, list):
            parts = [item.strip() for item in value if isinstance(item, str) and item.strip()]
            if parts:
                return '\n'.join(parts)
        if isinstance(value, dict):
            nested_parts = []
            for nested_key in ['en', 'text', 'content', 'message', 'body']:
                nested_val = value.get(nested_key)
                if isinstance(nested_val, str) and nested_val.strip():
                    nested_parts.append(nested_val.strip())
            if nested_parts:
                return '\n'.join(nested_parts)

    return ''

def fix_mojibake(text):
    """Fix double-encoded UTF-8 text (e.g. â€' -> ‑).
    
    This occurs when UTF-8 bytes are misinterpreted as Latin-1/Windows-1252.
    """
    try:
        return text.encode('latin-1').decode('utf-8')
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text

def changelog_to_plain_text(changelog_text):
    """Convert changelog content to plain text by removing HTML markup."""
    if not changelog_text:
        return ''

    text = changelog_text
    # Fix potential mojibake (double-encoded UTF-8 from upstream API)
    text = fix_mojibake(text)
    # Preserve visual structure for common block/list tags before stripping all tags.
    text = re.sub(r'(?i)<\s*br\s*/?\s*>', '\n', text)
    text = re.sub(r'(?i)</\s*(p|div|h1|h2|h3|h4|h5|h6|li|ul|ol)\s*>', '\n', text)
    text = re.sub(r'(?is)<\s*script[^>]*>.*?<\s*/\s*script\s*>', '', text)
    text = re.sub(r'(?is)<\s*style[^>]*>.*?<\s*/\s*style\s*>', '', text)
    text = re.sub(r'(?s)<[^>]+>', '', text)
    text = html_lib.unescape(text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

def fetch_data(url):
    try:
        req = urllib.request.Request(url)
        req.add_header('User-Agent', 'Mozilla/5.0')
        with urllib.request.urlopen(req) as response:
            if response.status == 200:
                raw = response.read()
                charset = response.headers.get_content_charset('utf-8')
                data = json.loads(raw.decode(charset))
                if 'info' in data:
                    return data['info']
    except Exception as e:
        message = f"API request failed for {url}: {type(e).__name__}: {e}"
        print(f"  ERROR {message}")
        log_annotation('error', message)
    return []

def fetch_data_individual(model_codes):
    all_info = []
    empty_models = []
    model_codes = list(model_codes)
    total = len(model_codes)
    for idx, model in enumerate(model_codes):
        entries = fetch_data(f"{API_URL}?model={model}")
        entries += fetch_data(f"{API_URL}?model={model}-open")
        log_progress(f"[{idx+1}/{total}] {model}: {len(entries)} firmware entries")
        if not entries:
            message = f"{model}: API returned no firmware entries"
            print(f"  WARNING {message}")
            log_annotation('warning', message)
            empty_models.append(model)
        all_info.extend(entries)
        time.sleep(0.1) # Be nice to the API

    print(f"Fetched {len(all_info)} firmware entries for {total} models.")
    return {'info': all_info}, empty_models

def detect_openwrt_base(entry):
    """Determine the OpenWrt base major version ('24', '25', ...) of an
    'open' firmware entry from its download filename
    (e.g. 'mt3000-op-4.9.1-op25_beta1-...bin'). Returns None if unknown."""
    try:
        link = entry.get('download', [{}])[0].get('link', '') or ''
    except (IndexError, AttributeError, TypeError):
        link = ''
    match = re.search(r'-op(\d{2})', link)
    return match.group(1) if match else None

def bucket_entries(entries):
    """Group API entries into buckets[model_code][stage] = [entry, ...]."""
    buckets = {}
    for entry in entries:
        model_code = entry.get('model')
        stage = entry.get('stage')

        if not model_code or not stage:
            continue

        if model_code.endswith('-open'):
            model_code = model_code[:-5]
            base = detect_openwrt_base(entry) or '24'
            stage = f'BETA_OPEN{base}'
            entry['_is_open'] = True
            entry['_openwrt_base'] = base

        if stage == 'TESTING':
            stage = 'BETA'

        buckets.setdefault(model_code, {}).setdefault(stage, []).append(entry)
    return buckets

def entry_link(entry):
    if entry.get('download'):
        return entry['download'][0].get('link', '') or ''
    return ''

def process_data(data, models_metadata):
    """Keep the newest firmware the API reports per model and stage.

    The download link is verified, but a link that does not respond never
    changes which version is published: reporting an older release as the
    current one is worse than reporting the current one without a working
    download. An unreachable link is marked as such instead, and the reason
    ends up in the build log, on the status page and in /api/status.json.
    """
    if not data or 'info' not in data:
        return {}, []

    buckets = bucket_entries(data['info'])

    # Structure: models[model_code][stage] = firmware_info
    models = {code: {} for code in models_metadata}
    diagnostics = []

    # Keep the metadata order so the log matches the fetch order above.
    ordered_codes = [c for c in models_metadata if c in buckets]
    ordered_codes += [c for c in buckets if c not in models_metadata]
    total = len(ordered_codes)

    for idx, model_code in enumerate(ordered_codes):
        models.setdefault(model_code, {})
        summary = []
        problems = []

        for stage in sorted(buckets[model_code]):
            candidates = sorted(buckets[model_code][stage],
                                key=lambda e: e.get('release_time', ''),
                                reverse=True)
            newest = candidates[0]
            link = entry_link(newest)
            ok, reason, attempts, duration = check_link(link)

            # The newest version stays published either way, but when its own
            # download is dead, offer the newest older build that still works.
            fallback, fallback_link, probed = (None, '', 0)
            if not ok:
                fallback, fallback_link, probed = find_reachable_fallback(candidates[1:])

            stored = dict(newest)
            stored['changelog'] = changelog_to_plain_text(extract_changelog(newest))
            stored['_link_ok'] = ok
            stored['_link_reason'] = reason
            if fallback is not None:
                stored['_fallback_version'] = fallback.get('version', 'N/A')
                stored['_fallback_link'] = fallback_link
                stored['_fallback_release_time'] = fallback.get('release_time', '')
            models[model_code][stage] = stored

            version = newest.get('version', 'N/A')
            diagnostics.append({
                'model': model_code,
                'name': models_metadata.get(model_code, {}).get('name', model_code),
                'stage': stage,
                'status': 'ok' if ok else 'unreachable',
                'version': version,
                'release_time': newest.get('release_time', ''),
                'link': link,
                'reason': reason,
                'attempts': attempts,
                'duration': duration,
                'candidates_probed': probed,
                'fallback_version': fallback.get('version', 'N/A') if fallback else None,
                'fallback_release_time': fallback.get('release_time', '') if fallback else '',
                'fallback_link': fallback_link,
            })

            if ok:
                summary.append(f"{stage} {version}")
            elif fallback is not None:
                summary.append(f"{stage} {version} (link dead, offering "
                               f"{fallback.get('version', 'N/A')})")
                problems.append(diagnostics[-1])
            else:
                summary.append(f"{stage} {version} (link unreachable)")
                problems.append(diagnostics[-1])

        log_progress(f"[{idx+1}/{total}] {model_code}: " + " · ".join(summary))

        for d in problems:
            tries = "attempt" if d['attempts'] == 1 else "attempts"
            print(f"  WARNING {model_code} ({d['stage']}) {d['version']}: download unreachable after "
                  f"{d['attempts']} {tries} ({d['reason']}, {d['duration']}s). "
                  f"Version is still published.")
            print(f"          {d['link'] or '<no link>'}")
            if d['fallback_version']:
                print(f"          offering {d['fallback_version']} instead as the newest reachable "
                      f"download ({d['candidates_probed']} older build(s) probed)")
                extra = f", offering {d['fallback_version']} as the newest reachable download"
            else:
                extra = (f", and none of the {d['candidates_probed']} older build(s) probed responded"
                         if d['candidates_probed'] else "")
            log_annotation('warning', f"{model_code} ({d['stage']}) {d['version']}: download link "
                                      f"unreachable ({d['reason']}) after {d['attempts']} {tries}{extra}")

    unreachable = sum(1 for d in diagnostics if d['status'] == 'unreachable')
    with_fallback = sum(1 for d in diagnostics if d['fallback_version'])
    attempts = sum(d['attempts'] + d['candidates_probed'] for d in diagnostics)
    offered = f" ({with_fallback} with an older reachable build to offer)" if unreachable else ""
    print(f"Processing complete: {len(diagnostics)} model/stage entries, {attempts} HEAD requests, "
          f"{unreachable} unreachable download{'' if unreachable == 1 else 's'}{offered}. "
          f"Retry budget left: {max(0, round(_retry_budget_left))}s of {RETRY_BUDGET}s.")
    return models, diagnostics

# ---------------------------------------------------------------------------
# Shared rendering helpers
# ---------------------------------------------------------------------------

def api_stage_name(stage):
    """Map an internal stage key to its lowercase API path segment (BETA_OPEN24 -> beta-open24)."""
    return stage.lower().replace('_open', '-open')

def base_stage(stage):
    """Stage name used for labels and colors (BETA_OPEN24 -> BETA)."""
    return 'BETA' if stage.startswith('BETA_OPEN') else stage

def stage_label(stage, entry=None):
    """Human readable plain-text stage label, e.g. 'BETA (OP24)' for open variants."""
    if stage.startswith('BETA_OPEN'):
        base = (entry or {}).get('_openwrt_base') or stage[len('BETA_OPEN'):] or '24'
        return f'BETA (OP{base})'
    return stage

def ordered_stages(model_stages):
    """Order a model's stage keys for display: known stages first, unknown ones
    alphabetically, and OpenWrt open variants directly after BETA (they are
    rendered in the BETA column of the overview as well)."""
    regular = [s for s in model_stages if not s.startswith('BETA_OPEN')]
    open_variants = sorted(s for s in model_stages if s.startswith('BETA_OPEN'))
    ordered = [s for s in STAGE_ORDER if s in regular] + sorted(s for s in regular if s not in STAGE_ORDER)
    insert_at = ordered.index('BETA') + 1 if 'BETA' in ordered else len(ordered)
    return ordered[:insert_at] + open_variants + ordered[insert_at:]

def open_badge_html(entry):
    """Small 'OP24'/'OP25' badge for OpenWrt open variants, empty string otherwise."""
    if not entry.get('_is_open'):
        return ''
    base = entry.get('_openwrt_base', '24')
    return f'<span class="badge bg-secondary ms-1" style="font-size:0.6rem;vertical-align:middle;" title="OpenWrt {base} open variant">OP{base}</span>'

def device_page_url(code):
    """Site-relative URL of a model's device page ('mt3000/'), or None if the
    model code would collide with a reserved root directory."""
    slug = code.lower()
    if slug in RESERVED_ROOT_NAMES:
        return None
    return f"{slug}/"

def favicon_links_html(root=''):
    """<link> tags of the favicon set; `root` is the relative path to the site root."""
    return f"""    <link rel="icon" href="{root}favicon.ico" sizes="any">
    <link rel="icon" type="image/png" sizes="16x16" href="{root}images/favicon-16.png">
    <link rel="icon" type="image/png" sizes="32x32" href="{root}images/favicon-32.png">
    <link rel="icon" type="image/png" sizes="192x192" href="{root}images/favicon-192.png">
    <link rel="apple-touch-icon" sizes="180x180" href="{root}images/apple-touch-icon.png">
    <meta name="theme-color" content="{THEME_COLOR}">"""

def share_bar_html(url, title):
    """Row of share buttons: common networks as plain links, plus copy-link and
    (where the browser supports it) the native share sheet via SHARE_SCRIPT."""
    q_url = urllib.parse.quote(url, safe='')
    q_text = urllib.parse.quote(title, safe='')
    networks = [
        ('X', 'fa-brands fa-x-twitter', f'https://x.com/intent/post?url={q_url}&text={q_text}'),
        ('Reddit', 'fa-brands fa-reddit-alien', f'https://www.reddit.com/submit?url={q_url}&title={q_text}'),
        ('Facebook', 'fa-brands fa-facebook-f', f'https://www.facebook.com/sharer/sharer.php?u={q_url}'),
        ('Telegram', 'fa-brands fa-telegram', f'https://t.me/share/url?url={q_url}&text={q_text}'),
        ('WhatsApp', 'fa-brands fa-whatsapp', f'https://wa.me/?text={q_text}%20{q_url}'),
        ('Email', 'fa-solid fa-envelope', f'mailto:?subject={q_text}&body={q_url}'),
    ]
    buttons = []
    for name, icon, href in networks:
        target = ' target="_blank" rel="noopener"' if href.startswith('http') else ''
        buttons.append(f'<a href="{href}"{target} class="btn btn-outline-secondary" title="Share via {name}">'
                       f'<i class="{icon}"></i><span class="visually-hidden">{name}</span></a>')
    return f"""<div class="share-bar d-flex flex-wrap justify-content-center align-items-center gap-1" data-share-url="{html_lib.escape(url, quote=True)}" data-share-title="{html_lib.escape(title, quote=True)}">
                <span class="timestamp me-1"><i class="fas fa-share-nodes me-1"></i>Share:</span>
                {''.join(buttons)}
                <button type="button" class="btn btn-outline-secondary share-copy" title="Copy link to clipboard"><i class="fas fa-link me-1"></i>Copy link</button>
                <button type="button" class="btn btn-outline-secondary share-native d-none" title="Open the share sheet"><i class="fas fa-arrow-up-from-bracket me-1"></i>Share&hellip;</button>
            </div>"""

def html_head(title, description='', canonical='', root=''):
    """Shared <head>: Bootstrap, Font Awesome, common styles, favicons and the
    Open Graph / Twitter Card tags that give shared links a preview."""
    esc_title = html_lib.escape(title, quote=True)
    og_image = f"{SITE_URL}/{OG_IMAGE_PATH}"
    extra = ''
    if description:
        esc_desc = html_lib.escape(description, quote=True)
        extra += f'\n    <meta name="description" content="{esc_desc}">'
        extra += f'\n    <meta property="og:description" content="{esc_desc}">'
        extra += f'\n    <meta name="twitter:description" content="{esc_desc}">'
    if canonical:
        extra += f'\n    <link rel="canonical" href="{canonical}">'
        extra += f'\n    <meta property="og:url" content="{canonical}">'
    return f"""<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{esc_title}</title>
    <meta property="og:site_name" content="{SITE_NAME}">
    <meta property="og:title" content="{esc_title}">
    <meta property="og:type" content="website">
    <meta property="og:image" content="{og_image}">
    <meta property="og:image:width" content="{OG_IMAGE_SIZE[0]}">
    <meta property="og:image:height" content="{OG_IMAGE_SIZE[1]}">
    <meta property="og:image:alt" content="{SITE_NAME}">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{esc_title}">
    <meta name="twitter:image" content="{og_image}">{extra}
{favicon_links_html(root)}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <style>{PAGE_STYLE}    </style>
</head>"""

# ---------------------------------------------------------------------------
# Overview page (index.html)
# ---------------------------------------------------------------------------

def generate_html(models, models_metadata, diagnostics, generated_at=None):
    generated_at = generated_at or datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')
    # Group models by type
    grouped_models = {'ROUTER': [], 'IOT': [], 'KVM': []}
    for code in models.keys():
        meta = models_metadata.get(code, {})
        m_type = meta.get('type', 'ROUTER')
        if m_type not in grouped_models:
            grouped_models[m_type] = []
        grouped_models[m_type].append(code)

    # Sort within each group
    def get_sort_key(code):
        meta = models_metadata.get(code, {})
        return meta.get('name', code)

    for m_type in grouped_models:
        grouped_models[m_type].sort(key=get_sort_key)
    
    # Collect all unique stages to create table headers, exclude internal BETA_OPEN* variants
    all_stages = set()
    for model in models:
        all_stages.update(s for s in models[model].keys() if not s.startswith('BETA_OPEN'))
    
    # Define a preferred order for columns
    sorted_stages = [s for s in STAGE_ORDER if s in all_stages] + [s for s in sorted(all_stages) if s not in STAGE_ORDER]

    issue_count = sum(1 for d in diagnostics if d['status'] != 'ok')
    if issue_count:
        status_link = (f'<a href="status.html" class="text-decoration-none">'
                       f'<i class="fas fa-triangle-exclamation text-warning"></i> '
                       f'{issue_count} download{"" if issue_count == 1 else "s"} unreachable</a>')
    else:
        status_link = ('<a href="status.html" class="text-decoration-none">'
                       '<i class="fas fa-circle-check text-success"></i> All links verified</a>')

    head = html_head(
        SITE_NAME,
        description="Latest verified GL.iNet firmware versions for all routers, IoT and KVM devices, with a flat-file API.",
        canonical=f"{SITE_URL}/",
    )

    html = f"""
<!DOCTYPE html>
<html lang="en">
{head}
<body>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 text-center mb-4">
            <h1><i class="fas fa-microchip text-primary"></i> GL.iNet Firmware Overview</h1>
            <p class="lead">Latest verified firmware versions</p>
            <div class="mb-2">
                <span class="badge bg-info text-dark">Community Project by <a href="https://admon.me" target="_blank" class="text-dark text-decoration-none fw-bold">admon (admon.me)</a></span>
            </div>
            <p class="timestamp mb-1">Last updated: {generated_at}</p>
            <p class="timestamp">{status_link}</p>
            {share_bar_html(f"{SITE_URL}/", SITE_NAME)}
        </div>
    </div>

    <div class="row justify-content-center search-container">
        <div class="col-md-8">
            <div class="input-group">
                <span class="input-group-text bg-white"><i class="fas fa-search text-muted"></i></span>
                <input type="text" id="searchInput" class="form-control form-control-lg border-start-0" placeholder="Search for model (e.g. AX1800) or code (e.g. flint)...">
            </div>
        </div>
    </div>

    <div class="row justify-content-center mb-4">
        <div class="col-md-10">
            <div class="accordion shadow-sm" id="apiAccordion">
                <div class="accordion-item border-0">
                    <h2 class="accordion-header" id="headingAPI">
                        <button class="accordion-button collapsed fw-bold bg-white text-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAPI" aria-expanded="false" aria-controls="collapseAPI">
                            <i class="fas fa-code me-2"></i> How to use the Flat-File API
                        </button>
                    </h2>
                    <div id="collapseAPI" class="accordion-collapse collapse" aria-labelledby="headingAPI" data-bs-parent="#apiAccordion">
                        <div class="accordion-body api-info m-0 border-top">
                            <p class="small mb-2">
                                This dashboard provides a machine-readable flat-file API. You can access firmware information directly:
                            </p>
                            <ul class="small mb-0">
                                <li><strong>Available stages:</strong> <code>/api/&lt;model&gt;/branches</code> (e.g., <code>/api/ax1800/branches</code>)</li>
                                <li><strong>Version string:</strong> <code>/api/&lt;model&gt;/&lt;stage&gt;/version</code> (e.g., <code>/api/ax1800/release/version</code>)</li>
                                <li><strong>Download URL:</strong> <code>/api/&lt;model&gt;/&lt;stage&gt;/url</code></li>
                                <li><strong>Latest changelog:</strong> <code>/api/&lt;model&gt;/&lt;stage&gt;/changelog</code></li>
                                <li><strong>Specific attributes:</strong> <code>/api/&lt;model&gt;/&lt;stage&gt;/[version|url|date|hash|changelog]</code></li>
                                <li><strong>Consolidated data:</strong> <code>/api/all.json</code></li>
                                <li><strong>Build &amp; link status:</strong> <code>/api/status.json</code> (see the <a href="status.html">status page</a>)</li>
                                <li><strong>Device page (deep link):</strong> <code>/&lt;model&gt;/</code> (e.g., <a href="{device_page_url('ax1800')}"><code>/ax1800/</code></a>) &ndash; click a model name below</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    """

    for m_type in ['ROUTER', 'IOT', 'KVM']:
        codes = grouped_models.get(m_type, [])
        if not codes:
            continue
            
        icon = TYPE_ICONS.get(m_type, 'fa-device')
        name = TYPE_NAMES.get(m_type, m_type)

        html += f"""
    <h3 class="section-title" id="{m_type.lower()}"><i class="fas {icon} text-primary"></i> {name}</h3>
    <div class="card mb-5">
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover table-striped mb-0 firmware-table">
                    <thead class="table-dark">
                        <tr>
                            <th scope="col" class="ps-4" style="min-width: 200px;">Model</th>
                            {''.join([f'<th scope="col">{s}</th>' for s in sorted_stages])}
                        </tr>
                    </thead>
                    <tbody>
        """

        for code in codes:
            meta = models_metadata.get(code, {})
            full_name = html_lib.escape(meta.get('name', code))
            page_url = device_page_url(code)
            name_html = f'<a href="{page_url}" class="model-link" title="Open device page for {full_name}">{full_name} <i class="fas fa-link ms-1"></i></a>' if page_url else full_name
            
            html += f"""
            <tr id="{code.lower()}">
                <td class='ps-4'>
                    <div class="fw-bold">{name_html}</div>
                    <div class="text-muted small" style="font-size: 0.7rem;">{html_lib.escape(code)}</div>
                </td>
            """
            for stage in sorted_stages:
                info = models[code].get(stage)
                # Gather all OpenWrt "open" variants (op24, op25, ...) alongside the BETA column
                open_stages = sorted(s for s in models[code] if s.startswith('BETA_OPEN')) if stage == 'BETA' else []
                # (actual_stage, entry) pairs to render in this cell
                render_list = [(stage, info)] if info else []
                render_list += [(s, models[code][s]) for s in open_stages]
                if render_list:
                    cells = []
                    for entry_stage, entry_info in render_list:
                        version = entry_info.get('version', 'N/A')
                        release_time = entry_info.get('release_time', '').split(' ')[0]
                        download_link = entry_link(entry_info) or '#'
                        changelog_text = (entry_info.get('changelog') or '').strip()
                        timestamp_html = f'<span class="timestamp">{release_time}</span>'
                        if changelog_text:
                            changelog_path = f"api/{code.lower()}/{api_stage_name(entry_stage)}/changelog"
                            timestamp_html = f'<a class="timestamp text-decoration-none" href="{changelog_path}" target="_blank" title="Open latest changelog TXT">{release_time} <i class="fas fa-file-lines small ms-1"></i></a>'
                        open_badge = open_badge_html(entry_info)
                        fallback_html = ''
                        if entry_info.get('_link_ok', True):
                            version_html = (f'<a href="{download_link}" target="_blank" '
                                            f'class="fw-version text-decoration-none stage-{stage}">'
                                            f'{version} <i class="fas fa-download small ms-1"></i></a>')
                        else:
                            # The version stays published; only the download is marked as broken.
                            hint = html_lib.escape(
                                f"Download link unreachable ({entry_info.get('_link_reason', 'unknown')}) "
                                f"- see the status page", quote=True)
                            version_html = (f'<span class="fw-version text-muted">{version}</span> '
                                            f'<a href="status.html" class="text-decoration-none" title="{hint}">'
                                            f'<i class="fas fa-triangle-exclamation small text-warning"></i></a>')
                            if entry_info.get('_fallback_link'):
                                fb_version = entry_info['_fallback_version']
                                fb_link = html_lib.escape(entry_info['_fallback_link'], quote=True)
                                fallback_html = (
                                    f'<a href="{fb_link}" target="_blank" class="fallback-link text-decoration-none" '
                                    f'title="Newest version with a working download">'
                                    f'<i class="fas fa-download small me-1"></i>{fb_version} instead</a>')
                        cells.append(f'''
                                <div class="d-flex flex-column{'  border-top pt-1 mt-1' if entry_info.get('_is_open') and info else ''}">
                                    {version_html}
                                    <div>{timestamp_html}{open_badge}</div>
                                    {fallback_html}
                                </div>''')
                    html += f"<td>{''.join(cells)}</td>"
                else:
                    html += "<td><span class='text-muted'>-</span></td>"
            html += "</tr>"

        html += """
                    </tbody>
                </table>
            </div>
        </div>
    </div>
        """

    html += """
    <footer>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <p class="mb-0 mt-3 small">Data is automatically verified and updated daily from GL.iNet Firmware API.</p>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
    document.getElementById('searchInput').addEventListener('keyup', function() {
        var input = this.value.toLowerCase();
        var tables = document.querySelectorAll('.firmware-table');
        
        tables.forEach(function(table) {
            var rows = table.querySelectorAll('tbody tr');
            var visibleRows = 0;
            
            rows.forEach(function(row) {
                var text = row.textContent.toLowerCase();
                if (text.includes(input)) {
                    row.style.display = '';
                    visibleRows++;
                } else {
                    row.style.display = 'none';
                }
            });
            
            // Hide the entire table section if no rows are visible
            var card = table.closest('.card');
            var title = card.previousElementSibling;
            if (visibleRows === 0) {
                card.style.display = 'none';
                if (title && title.classList.contains('section-title')) {
                    title.style.display = 'none';
                }
            } else {
                card.style.display = '';
                if (title && title.classList.contains('section-title')) {
                    title.style.display = '';
                }
            }
        });
    });
</script>
""" + SHARE_SCRIPT + """
</body>
</html>
    """
    return html

# ---------------------------------------------------------------------------
# Device pages (<model>/index.html at the site root)
# ---------------------------------------------------------------------------

def generate_device_page(code, stages, meta, generated_at):
    """Build the standalone HTML page of a single model, served at /<model>/."""
    code_lower = code.lower()
    full_name = meta.get('name', code)
    m_type = meta.get('type', 'ROUTER')
    icon = TYPE_ICONS.get(m_type, 'fa-microchip')
    type_name = TYPE_NAMES.get(m_type, m_type)
    esc_name = html_lib.escape(full_name)
    esc_code = html_lib.escape(code)
    canonical = f"{SITE_URL}/{device_page_url(code)}"
    # Device pages live one directory level below the site root
    root = '../'
    api_rel = f"{root}api/{code_lower}"
    api_abs = f"{SITE_URL}/api/{code_lower}"

    display_stages = ordered_stages(stages)

    summary_parts = []
    rows = []
    changelog_blocks = []
    endpoint_items = []
    for stage in display_stages:
        info = stages[stage]
        s_api = api_stage_name(stage)
        label = base_stage(stage)
        version = info.get('version', 'N/A')
        esc_version = html_lib.escape(version)
        release_time = info.get('release_time', '')
        release_date = release_time.split(' ')[0]
        download_link = html_lib.escape(entry_link(info) or '#', quote=True)
        md5_hash = (info.get('download') or [{}])[0].get('md5', '') or ''
        changelog_text = (info.get('changelog') or '').strip()
        badge = open_badge_html(info)
        link_ok = info.get('_link_ok', True)

        summary_parts.append(f"{stage_label(stage, info)} {version}")

        hash_html = f'<div class="timestamp font-monospace" title="MD5">MD5 {html_lib.escape(md5_hash)}</div>' if md5_hash else ''
        if link_ok:
            version_html = f'<span class="fw-version">{esc_version}</span>'
            download_cell = (f'<a href="{download_link}" target="_blank" class="btn btn-sm btn-outline-primary text-nowrap">'
                             f'<i class="fas fa-download me-1"></i>Download</a>')
        else:
            # The version stays published; only the download is marked as broken (same rule as the overview).
            hint = html_lib.escape(
                f"Download link unreachable ({info.get('_link_reason', 'unknown')}) - see the status page", quote=True)
            version_html = f'<span class="fw-version text-muted">{esc_version}</span>'
            download_cell = (f'<a href="{root}status.html" class="badge bg-warning text-dark text-decoration-none" title="{hint}">'
                             f'<i class="fas fa-triangle-exclamation me-1"></i>Unreachable</a>')
            if info.get('_fallback_link'):
                fb_link = html_lib.escape(info['_fallback_link'], quote=True)
                fb_version = html_lib.escape(info.get('_fallback_version', 'N/A'))
                download_cell += (f'<div class="mt-1"><a href="{fb_link}" target="_blank" class="btn btn-sm btn-outline-secondary text-nowrap" '
                                  f'title="Newest version with a working download"><i class="fas fa-download me-1"></i>{fb_version} instead</a></div>')

        if changelog_text:
            changelog_cell = f'<a href="#changelog-{s_api}" class="text-decoration-none" title="Jump to changelog"><i class="fas fa-file-lines me-1"></i>Changelog</a>'
            changelog_blocks.append(f"""
                <details id="changelog-{s_api}" class="mb-3"{' open' if not changelog_blocks else ''}>
                    <summary class="fw-bold"><span class="stage-{label}">{label}</span>{badge} <span class="fw-version">{esc_version}</span> <span class="timestamp ms-1">{html_lib.escape(release_date)}</span>
                        <a href="{api_rel}/{s_api}/changelog" target="_blank" class="small text-decoration-none ms-2" title="Open as plain text">TXT <i class="fas fa-arrow-up-right-from-square small"></i></a></summary>
                    <pre class="changelog-text mt-2">{html_lib.escape(changelog_text)}</pre>
                </details>""")
        else:
            changelog_cell = '<span class="text-muted">-</span>'

        rows.append(f"""
                        <tr id="{s_api}">
                            <td class="ps-4"><span class="fw-bold stage-{label}">{label}</span>{badge}</td>
                            <td>{version_html}{hash_html}</td>
                            <td class="text-nowrap"><span class="timestamp" title="{html_lib.escape(release_time, quote=True)}">{html_lib.escape(release_date)}</span></td>
                            <td>{download_cell}</td>
                            <td>{changelog_cell}</td>
                        </tr>""")

        attr_links = ' &middot; '.join(
            f'<a href="{api_rel}/{s_api}/{attr}" target="_blank">{attr}</a>'
            for attr in ['version', 'url', 'date', 'hash', 'changelog']
        )
        endpoint_items.append(f'<li class="mb-1"><strong>{label}{badge}:</strong> <code>{api_abs}/{s_api}/</code> <span class="ms-1">[ {attr_links} ]</span></li>')

    if rows:
        firmware_section = f"""
    <h3 class="section-title"><i class="fas fa-download text-primary"></i> Firmware versions</h3>
    <div class="card">
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover table-striped mb-0 align-middle">
                    <thead class="table-dark">
                        <tr>
                            <th scope="col" class="ps-4">Stage</th>
                            <th scope="col">Version</th>
                            <th scope="col">Released</th>
                            <th scope="col">Download</th>
                            <th scope="col">Changelog</th>
                        </tr>
                    </thead>
                    <tbody>{''.join(rows)}
                    </tbody>
                </table>
            </div>
        </div>
    </div>"""
        example_stage = api_stage_name(display_stages[0])
    else:
        firmware_section = """
    <div class="alert alert-warning shadow-sm" role="alert">
        <i class="fas fa-triangle-exclamation me-2"></i> No verified firmware download is currently available for this model.
    </div>"""
        example_stage = 'release'

    changelog_section = ''
    if changelog_blocks:
        changelog_section = f"""
    <h3 class="section-title"><i class="fas fa-file-lines text-primary"></i> Changelogs</h3>
    <div class="card">
        <div class="card-body">{''.join(changelog_blocks)}
        </div>
    </div>"""

    description = f"Latest verified GL.iNet firmware for {full_name} ({code})"
    if summary_parts:
        description += ": " + ", ".join(summary_parts)
    description += "."

    head = html_head(f"{full_name} Firmware | {SITE_NAME}", description=description, canonical=canonical, root=root)

    return f"""<!DOCTYPE html>
{DEVICE_PAGE_MARKER}
<html lang="en">
{head}
<body>

<div class="container">
    <nav aria-label="breadcrumb" class="mb-3">
        <ol class="breadcrumb small mb-0">
            <li class="breadcrumb-item"><a href="{root}" class="text-decoration-none"><i class="fas fa-microchip me-1"></i>GL.iNet Firmware Overview</a></li>
            <li class="breadcrumb-item"><a href="{root}#{m_type.lower()}" class="text-decoration-none">{html_lib.escape(type_name)}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{esc_name}</li>
        </ol>
    </nav>

    <div class="row justify-content-center">
        <div class="col-12 text-center mb-4">
            <h1><i class="fas {icon} text-primary"></i> {esc_name}</h1>
            <p class="lead mb-2">Latest verified firmware versions</p>
            <div class="mb-2">
                <span class="badge bg-dark font-monospace">{esc_code}</span>
                <span class="badge bg-secondary">{html_lib.escape(type_name)}</span>
            </div>
            <p class="timestamp mb-1">Last updated: {generated_at}</p>
            <p class="timestamp">Permalink: <a href="{canonical}" class="text-decoration-none font-monospace">{canonical}</a></p>
            {share_bar_html(canonical, f"{full_name} firmware - {SITE_NAME}")}
        </div>
    </div>
{firmware_section}
{changelog_section}
    <h3 class="section-title"><i class="fas fa-code text-primary"></i> API endpoints for this device</h3>
    <div class="card">
        <div class="card-body api-info m-0">
            <ul class="small mb-2">
                <li class="mb-1"><strong>Available stages:</strong> <code>{api_abs}/branches</code> <span class="ms-1">[ <a href="{api_rel}/branches" target="_blank">open</a> ]</span></li>
                {''.join(endpoint_items)}
            </ul>
            <p class="small mb-0"><strong>Example:</strong> <code>curl -s {api_abs}/{example_stage}/version</code></p>
        </div>
    </div>

    <footer>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <p class="mb-2"><a href="{root}" class="text-decoration-none"><i class="fas fa-arrow-left me-1"></i> Back to the firmware overview</a></p>
                <p class="mb-0 mt-3 small">Data is automatically verified and updated daily from GL.iNet Firmware API.</p>
            </div>
        </div>
    </footer>
</div>
{SHARE_SCRIPT}
</body>
</html>
"""

def remove_stale_device_pages():
    """Delete root-level directories that hold a device page from a previous run.
    Only directories whose index.html carries DEVICE_PAGE_MARKER are touched."""
    for name in os.listdir('.'):
        page = os.path.join(name, 'index.html')
        if name in RESERVED_ROOT_NAMES or not os.path.isdir(name) or not os.path.isfile(page):
            continue
        with open(page, encoding='utf-8', errors='ignore') as f:
            if DEVICE_PAGE_MARKER in f.read(2048):
                shutil.rmtree(name)

def generate_device_pages(models, models_metadata, generated_at):
    """Write one standalone HTML page per model to <model>/index.html at the site
    root. Returns the number of pages written."""
    remove_stale_device_pages()

    written = 0
    for code, stages in models.items():
        page_url = device_page_url(code)
        if page_url is None:
            print(f"  WARNING Skipping device page for '{code}': it would collide with a reserved directory.")
            continue
        meta = models_metadata.get(code, {})
        page_dir = code.lower()
        os.makedirs(page_dir, exist_ok=True)
        with open(os.path.join(page_dir, 'index.html'), 'w', encoding='utf-8') as f:
            f.write(generate_device_page(code, stages, meta, generated_at))
        written += 1
    return written

STATUS_PAGE_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Build Status - GL.iNet Firmware Overview</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
""" + favicon_links_html() + """
    <style>
        body { background-color: #f8f9fa; padding-top: 20px; }
        .card { margin-bottom: 30px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border: none; }
        .card-header { background-color: #343a40; color: white; font-weight: bold; padding: 12px 20px; }
        .timestamp { font-size: 0.8rem; color: #6c757d; }
        .stat-card { background: #fff; border-radius: 8px; padding: 18px; text-align: center;
                     box-shadow: 0 4px 6px rgba(0,0,0,0.08); height: 100%; }
        .stat-value { font-size: 1.8rem; font-weight: bold; line-height: 1.1; }
        .stat-label { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 1px; color: #6c757d; }
        .reason { font-family: monospace; font-size: 0.85rem; }
        .fw-version { font-family: monospace; font-weight: bold; }
        .file-link { font-family: monospace; font-size: 0.75rem; word-break: break-all; }
        .section-title { margin-bottom: 15px; font-weight: bold; color: #495057;
                         display: flex; align-items: center; }
        .section-title i { margin-right: 10px; }
        footer { margin-top: 50px; padding: 40px 0; text-align: center; color: #6c757d;
                 font-size: 0.9rem; border-top: 1px solid #dee2e6; }
    </style>
</head>
<body>
<div class="container">
"""

def stat_card(value, label, color=''):
    color_class = f' text-{color}' if color else ''
    return f"""
        <div class="col-6 col-md-4 col-lg-2 mb-3">
            <div class="stat-card">
                <div class="stat-value{color_class}">{value}</div>
                <div class="stat-label">{label}</div>
            </div>
        </div>"""

def generate_status_html(diagnostics, empty_models):
    esc = html_lib.escape

    unreachable = [d for d in diagnostics if d['status'] == 'unreachable']
    attempts = sum(d['attempts'] + d['candidates_probed'] for d in diagnostics)

    html = STATUS_PAGE_HEAD
    html += f"""
    <div class="row justify-content-center">
        <div class="col-12 text-center mb-4">
            <h1><i class="fas fa-heart-pulse text-primary"></i> Build &amp; Link Status</h1>
            <p class="lead">Which firmware downloads could not be reached</p>
            <p class="timestamp mb-1">Last build: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
            <p class="timestamp"><a href="index.html" class="text-decoration-none">
                <i class="fas fa-arrow-left"></i> Back to the firmware overview</a></p>
        </div>
    </div>

    <div class="alert alert-light border shadow-sm">
        <h5 class="alert-heading"><i class="fas fa-circle-info text-primary me-2"></i>How the check works</h5>
        <p class="mb-2 small">
            The overview always lists the newest firmware the GL.iNet API reports. Its download link is
            verified with a <code>HEAD</code> request ({LINK_TIMEOUT}s timeout, up to {LINK_ATTEMPTS}
            attempts for temporary failures). A link that does not respond never changes which version is
            listed &ndash; showing an older release as the current one would be worse than showing the
            current one without a working download. Instead the entry keeps its version, and on the
            overview its download is greyed out and flagged with a warning sign. Where an older build
            still downloads, the overview offers that one as a second link so there is always
            something to grab.
        </p>
        <p class="mb-0 small">
            A <span class="badge bg-warning text-dark">timeout</span> is usually temporary and resolves
            itself on the next daily run. An <span class="badge bg-danger">HTTP 404</span> means the file
            is really gone from GL.iNet's server; that one will not fix itself.
        </p>
    </div>

    <div class="row justify-content-center mb-4">"""

    html += stat_card(len(diagnostics), 'Model / stage entries')
    html += stat_card(attempts, 'HEAD requests')
    html += stat_card(len(unreachable), 'Unreachable downloads', 'danger' if unreachable else 'success')
    html += stat_card(len(empty_models), 'Models without API data', 'danger' if empty_models else 'success')
    html += """
    </div>
"""

    if not unreachable and not empty_models:
        html += """
    <div class="alert alert-success shadow-sm">
        <i class="fas fa-circle-check me-2"></i>
        Every tracked model and stage is showing the newest firmware the GL.iNet API reports,
        and every download link responded. Nothing to report.
    </div>
"""

    if empty_models:
        html += """
    <h3 class="section-title"><i class="fas fa-plug-circle-xmark text-danger"></i> Models without API data</h3>
    <div class="card">
        <div class="card-body">
            <p class="small mb-2">
                The GL.iNet API returned no firmware entries for these models during this build, so they
                carry no versions on the overview. This is almost always a temporary API hiccup.
            </p>
            <p class="mb-0">"""
        html += ' '.join(f'<span class="badge bg-secondary">{esc(m)}</span>' for m in empty_models)
        html += """</p>
        </div>
    </div>
"""

    if unreachable:
        html += """
    <h3 class="section-title"><i class="fas fa-link-slash text-danger"></i> Unreachable downloads</h3>
    <div class="card">
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover table-striped mb-0">
                    <thead class="table-dark">
                        <tr>
                            <th scope="col" class="ps-4" style="min-width: 200px;">Model</th>
                            <th scope="col">Stage</th>
                            <th scope="col">Version</th>
                            <th scope="col">Released</th>
                            <th scope="col">Reason</th>
                            <th scope="col">Attempts</th>
                            <th scope="col">Latest reachable</th>
                            <th scope="col">File</th>
                        </tr>
                    </thead>
                    <tbody>
"""
        for d in sorted(unreachable, key=lambda d: (d['model'], d['stage'])):
            filename = d['link'].rsplit('/', 1)[-1] if d['link'] else ''
            file_cell = (f'<a class="file-link" href="{esc(d["link"], quote=True)}" target="_blank" '
                         f'rel="noopener">{esc(filename)}</a>') if d['link'] else '<span class="text-muted">-</span>'
            if d['fallback_version']:
                fallback_cell = (
                    f'<a class="fw-version text-decoration-none" href="{esc(d["fallback_link"], quote=True)}" '
                    f'target="_blank" rel="noopener"><i class="fas fa-download small me-1"></i>'
                    f'{esc(d["fallback_version"])}</a>'
                    f'<div class="timestamp">{esc(d["fallback_release_time"].split(" ")[0])}</div>')
            else:
                fallback_cell = (f'<span class="text-muted small">none '
                                 f'({d["candidates_probed"]} probed)</span>')
            html += f"""
                        <tr>
                            <td class="ps-4">
                                <div class="fw-bold">{esc(d['name'])}</div>
                                <div class="text-muted small" style="font-size: 0.7rem;">{esc(d['model'])}</div>
                            </td>
                            <td>{esc(d['stage'])}</td>
                            <td><span class="fw-version">{esc(d['version'])}</span></td>
                            <td><span class="timestamp">{esc(d['release_time'].split(' ')[0])}</span></td>
                            <td><span class="reason">{esc(d['reason'])}</span></td>
                            <td>{d['attempts']}</td>
                            <td>{fallback_cell}</td>
                            <td>{file_cell}</td>
                        </tr>"""
        html += f"""
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer bg-white small text-muted">
            These versions are still listed on the overview &ndash; only their download link did not
            respond during this build. <em>Latest reachable</em> is the newest older build whose download
            still works (up to {FALLBACK_CANDIDATES} are probed); the overview offers it as a
            second link so there is always something to download.
        </div>
    </div>
"""

    html += """
    <footer>
        <p class="mb-0">Machine-readable version of this page: <code><a href="api/status.json">/api/status.json</a></code></p>
        <p class="mb-0 mt-3 small">Data is automatically verified and updated daily from GL.iNet Firmware API.</p>
    </footer>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
"""
    return html

def write_step_summary(diagnostics, empty_models):
    """Render the same findings into the GitHub Actions job summary."""
    path = os.environ.get('GITHUB_STEP_SUMMARY')
    if not path:
        return

    unreachable = [d for d in diagnostics if d['status'] == 'unreachable']

    lines = ['## Firmware link check', '']
    lines.append(f"- Model/stage entries: **{len(diagnostics)}**")
    lines.append(f"- HEAD requests: "
                 f"**{sum(d['attempts'] + d['candidates_probed'] for d in diagnostics)}**")
    lines.append(f"- Unreachable downloads: **{len(unreachable)}**")
    lines.append(f"- Models without API data: **{len(empty_models)}**")
    lines.append('')

    if empty_models:
        lines.append(f"\u26a0\ufe0f No API data for: {', '.join(empty_models)}")
        lines.append('')

    if unreachable:
        lines.append('The versions below are still published; only their download link failed.')
        lines.append('')
        lines.append('| Model | Stage | Version | Reason | Attempts | Latest reachable |')
        lines.append('| --- | --- | --- | --- | --- | --- |')
        for d in sorted(unreachable, key=lambda d: (d['model'], d['stage'])):
            fallback = d['fallback_version'] or f"none ({d['candidates_probed']} probed)"
            lines.append(f"| {d['model']} | {d['stage']} | {d['version']} | `{d['reason']}` "
                         f"| {d['attempts']} | {fallback} |")
    else:
        lines.append('\u2705 Every download link responded.')

    lines.append('')
    with open(path, 'a', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

def generate_api_files(models, diagnostics, empty_models):
    api_dir = 'api'
    if os.path.exists(api_dir):
        shutil.rmtree(api_dir)
    os.makedirs(api_dir)
    
    # Also generate a consolidated JSON
    all_data = {}

    for model_code, stages in models.items():
        model_code_lower = model_code.lower()
        model_dir = os.path.join(api_dir, model_code_lower)
        if not os.path.exists(model_dir):
            os.makedirs(model_dir)
        
        # List available branches/stages for this model
        available_stages = sorted([api_stage_name(s) for s in stages.keys()])
        branches_content = '\n'.join(available_stages) + '\n'
        
        # 1. Provide at api/model_code/branches
        with open(os.path.join(model_dir, 'branches'), 'w') as f:
            f.write(branches_content)
            
        # 2. Provide at api/model_code/index.html (served as /api/model_code/)
        with open(os.path.join(model_dir, 'index.html'), 'w') as f:
            f.write(branches_content)
            
        all_data[model_code_lower] = {}
        
        for stage, info in stages.items():
            s_name = api_stage_name(stage)
            version = info.get('version', 'N/A')
            release_time = info.get('release_time', '')
            download_url = info.get('download', [{}])[0].get('link', '')
            # Try to find a hash (md5 is common in GL.iNet API)
            md5_hash = info.get('download', [{}])[0].get('md5', '')
            changelog = (info.get('changelog') or '').strip()
            changelog_path = f"{SITE_URL}/api/{model_code_lower}/{s_name}/changelog"
            link_ok = info.get('_link_ok', True)
            link_state = 'ok' if link_ok else f"unreachable ({info.get('_link_reason', 'unknown')})"

            summary_content = (f"version: {version}\nhash: {md5_hash}\ndownload: {download_url}\n"
                               f"date: {release_time}\nchangelog: {changelog_path}\nlink: {link_state}\n")

            all_data[model_code_lower][s_name] = {
                'version': version,
                'release_time': release_time,
                'download': download_url,
                'md5': md5_hash,
                'changelog': changelog_path,
                'link_ok': link_ok
            }

            # Only present when this entry's own download did not respond.
            if info.get('_fallback_link'):
                all_data[model_code_lower][s_name]['latest_reachable'] = {
                    'version': info['_fallback_version'],
                    'release_time': info.get('_fallback_release_time', ''),
                    'download': info['_fallback_link'],
                }
                summary_content += (f"latest_reachable: {info['_fallback_version']} "
                                    f"{info['_fallback_link']}\n")
            
            # Simple structure: api/model/stage/attribute
            stage_path = os.path.join(model_dir, s_name)
            
            # If a file exists where we want a directory, remove it
            if os.path.exists(stage_path) and not os.path.isdir(stage_path):
                os.remove(stage_path)
            
            if not os.path.exists(stage_path):
                os.makedirs(stage_path)
            
            # Summary file at the stage directory level
            with open(os.path.join(stage_path, 'index.html'), 'w') as f:
                f.write(summary_content)
            
            # Sub-files for specific attributes
            with open(os.path.join(stage_path, 'version'), 'w') as f:
                f.write(version + '\n')
            with open(os.path.join(stage_path, 'url'), 'w') as f:
                f.write(download_url + '\n')
            with open(os.path.join(stage_path, 'date'), 'w') as f:
                f.write(release_time + '\n')
            with open(os.path.join(stage_path, 'hash'), 'w') as f:
                f.write(md5_hash + '\n')
            with open(os.path.join(stage_path, 'changelog'), 'w', encoding='utf-8') as f:
                f.write(changelog + '\n')

    with open(os.path.join(api_dir, 'all.json'), 'w', encoding='utf-8') as f:
        json.dump(all_data, f, indent=2, ensure_ascii=False)

    unreachable = [d for d in diagnostics if d['status'] == 'unreachable']
    status_data = {
        'generated_at': datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC'),
        'link_timeout_seconds': LINK_TIMEOUT,
        'link_attempts': LINK_ATTEMPTS,
        'summary': {
            'entries': len(diagnostics),
            'head_requests': sum(d['attempts'] + d['candidates_probed'] for d in diagnostics),
            'unreachable': len(unreachable),
            'models_without_api_data': len(empty_models),
        },
        'models_without_api_data': empty_models,
        'unreachable': unreachable,
    }
    with open(os.path.join(api_dir, 'status.json'), 'w', encoding='utf-8') as f:
        json.dump(status_data, f, indent=2, ensure_ascii=False)

def main():
    print("Loading models metadata...")
    models_metadata = {}
    if os.path.exists('models.json'):
        with open('models.json', 'r') as f:
            models_metadata = json.load(f)
    
    if not models_metadata:
        print("No models metadata found. Please run fetch_all_models.py first.")
        exit(1)

    print(f"Fetching firmware data for {len(models_metadata)} models...")
    raw_data, empty_models = fetch_data_individual(models_metadata.keys())

    if raw_data and raw_data.get('info'):
        print(f"Data fetched. Validating download links for {len(raw_data['info'])} entries...")
        models, diagnostics = process_data(raw_data, models_metadata)
        generated_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')

        print("Generating API files...")
        generate_api_files(models, diagnostics, empty_models)

        print(f"Generating device pages for {len(models)} models...")
        pages_written = generate_device_pages(models, models_metadata, generated_at)

        print(f"Generating HTML for {len(models)} models...")
        with open('index.html', 'w', encoding='utf-8') as f:
            f.write(generate_html(models, models_metadata, diagnostics, generated_at))

        print("Generating status page...")
        with open('status.html', 'w', encoding='utf-8') as f:
            f.write(generate_status_html(diagnostics, empty_models))

        write_step_summary(diagnostics, empty_models)
        print(f"Done. index.html, status.html, api/ files and {pages_written} device pages created.")
    else:
        message = "Failed to fetch or process data: the API returned no firmware entries at all."
        print(message)
        log_annotation('error', message)
        exit(1)



if __name__ == "__main__":
    main()
