import urllib.request
import json
import html as html_lib
import re
from datetime import datetime, timezone
import os
import shutil
import time

API_URL = "https://firmware-api.gl-inet.com/cloud-api/model/info"
# Public base URL of the deployed site (absolute links in API files and device pages)
SITE_URL = "https://glinet-firmware.admon.me"
# Per-model pages are generated at the site root (/<model>/index.html). Root entries
# that a model page must never overwrite:
RESERVED_ROOT_NAMES = {'api', 'images', 'cloudflare', '.git', '.github', '.claude'}
# Marker embedded in generated model pages so stale ones can be removed safely
DEVICE_PAGE_MARKER = '<!-- generated by generate_page.py (device page) -->'

# Preferred order of firmware stages; unknown stages follow alphabetically
STAGE_ORDER = ['RELEASE', 'BETA', 'SNAPSHOT', 'RC']

TYPE_ICONS = {
    'ROUTER': 'fa-wifi',
    'IOT': 'fa-broadcast-tower',
    'KVM': 'fa-server'
}

TYPE_NAMES = {
    'ROUTER': 'Routers',
    'IOT': 'IoT Devices',
    'KVM': 'KVM / Comet Series'
}

# Styles shared by the overview and the device pages
PAGE_STYLE = """
        body { background-color: #f8f9fa; padding-top: 20px; }
        .card { margin-bottom: 30px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border: none; }
        .card-header { background-color: #343a40; color: white; font-weight: bold; padding: 12px 20px; }
        .badge-stage { font-size: 0.8em; }
        .table-hover tbody tr:hover { background-color: #f1f1f1; }
        .fw-version { font-family: monospace; font-weight: bold; }
        .timestamp { font-size: 0.8rem; color: #6c757d; }
        .search-container { margin-bottom: 30px; }
        footer { margin-top: 50px; padding: 40px 0; text-align: center; color: #6c757d; font-size: 0.9rem; border-top: 1px solid #dee2e6; }

        /* Stage specific colors */
        .stage-RELEASE { color: #198754; }
        .stage-BETA { color: #0d6efd; }
        .stage-SNAPSHOT { color: #0dcaf0; }
        .stage-TESTING { color: #dc3545; }
        .stage-RC { color: #fd7e14; }

        .model-type { font-size: 0.7rem; text-transform: uppercase; color: #adb5bd; letter-spacing: 1px; }
        .api-info { background: #e9ecef; border-radius: 8px; padding: 20px; margin-bottom: 30px; }
        code { background: #f1f3f5; padding: 2px 4px; border-radius: 4px; color: #d63384; }
        .section-title { margin-bottom: 15px; font-weight: bold; color: #495057; display: flex; align-items: center; }
        .section-title i { margin-right: 10px; }

        /* Device pages */
        .model-link { color: inherit; text-decoration: none; }
        .model-link:hover { text-decoration: underline; }
        .model-link .fa-link { font-size: 0.7em; opacity: 0.4; }
        .changelog-text { white-space: pre-wrap; word-break: break-word; font-size: 0.85rem; background: #f1f3f5; border-radius: 8px; padding: 15px; margin: 0; }
        details summary { cursor: pointer; }
"""

def check_link(url):
    """Performs a HEAD request to check if the URL exists."""
    if not url or url == "#":
        return False
    try:
        req = urllib.request.Request(url, method='HEAD')
        req.add_header('User-Agent', 'Mozilla/5.0')
        with urllib.request.urlopen(req, timeout=5) as response:
            return response.status == 200
    except Exception:
        return False

def extract_changelog(entry):
    """Extract changelog text from known API field variants."""
    changelog_keys = [
        'changelog', 'release_notes', 'release_note', 'notes',
        'description', 'change_log', 'whats_new', 'what_is_new'
    ]

    for key in changelog_keys:
        value = entry.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
        if isinstance(value, list):
            parts = [item.strip() for item in value if isinstance(item, str) and item.strip()]
            if parts:
                return '\n'.join(parts)
        if isinstance(value, dict):
            nested_parts = []
            for nested_key in ['en', 'text', 'content', 'message', 'body']:
                nested_val = value.get(nested_key)
                if isinstance(nested_val, str) and nested_val.strip():
                    nested_parts.append(nested_val.strip())
            if nested_parts:
                return '\n'.join(nested_parts)

    return ''

def fix_mojibake(text):
    """Fix double-encoded UTF-8 text (e.g. â€' -> ‑).
    
    This occurs when UTF-8 bytes are misinterpreted as Latin-1/Windows-1252.
    """
    try:
        return text.encode('latin-1').decode('utf-8')
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text

def changelog_to_plain_text(changelog_text):
    """Convert changelog content to plain text by removing HTML markup."""
    if not changelog_text:
        return ''

    text = changelog_text
    # Fix potential mojibake (double-encoded UTF-8 from upstream API)
    text = fix_mojibake(text)
    # Preserve visual structure for common block/list tags before stripping all tags.
    text = re.sub(r'(?i)<\s*br\s*/?\s*>', '\n', text)
    text = re.sub(r'(?i)</\s*(p|div|h1|h2|h3|h4|h5|h6|li|ul|ol)\s*>', '\n', text)
    text = re.sub(r'(?is)<\s*script[^>]*>.*?<\s*/\s*script\s*>', '', text)
    text = re.sub(r'(?is)<\s*style[^>]*>.*?<\s*/\s*style\s*>', '', text)
    text = re.sub(r'(?s)<[^>]+>', '', text)
    text = html_lib.unescape(text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

def fetch_data(url):
    try:
        req = urllib.request.Request(url)
        req.add_header('User-Agent', 'Mozilla/5.0')
        with urllib.request.urlopen(req) as response:
            if response.status == 200:
                raw = response.read()
                charset = response.headers.get_content_charset('utf-8')
                data = json.loads(raw.decode(charset))
                if 'info' in data:
                    return data['info']
    except Exception as e:
        print(f"\nError fetching URL {url}: {e}")
        pass
    return []

def fetch_data_individual(model_codes):
    all_info = []
    total = len(model_codes)
    for idx, model in enumerate(model_codes):
        url = f"{API_URL}?model={model}"
        print(f"Fetching firmware info for {model} ({idx+1}/{total})...", end="\r")
        all_info.extend(fetch_data(url))
        all_info.extend(fetch_data(f"{API_URL}?model={model}-open"))
        time.sleep(0.1) # Be nice to the API
    
    print(f"\nFetched total {len(all_info)} firmware entries.")
    return {'info': all_info}

def detect_openwrt_base(entry):
    """Determine the OpenWrt base major version ('24', '25', ...) of an
    'open' firmware entry from its download filename
    (e.g. 'mt3000-op-4.9.1-op25_beta1-...bin'). Returns None if unknown."""
    try:
        link = entry.get('download', [{}])[0].get('link', '') or ''
    except (IndexError, AttributeError, TypeError):
        link = ''
    match = re.search(r'-op(\d{2})', link)
    return match.group(1) if match else None

def process_data(data, models_metadata):
    if not data or 'info' not in data:
        return {}

    # Structure: models[model_code][stage] = firmware_info
    models = {}
    
    # Initialize with all known models from metadata
    for code in models_metadata:
        models[code] = {}

    total_entries = len(data['info'])
    for idx, entry in enumerate(data['info']):
        model_code = entry.get('model')
        stage = entry.get('stage')
        
        if not model_code or not stage:
            continue

        if model_code.endswith('-open'):
            model_code = model_code[:-5]
            base = detect_openwrt_base(entry) or '24'
            stage = f'BETA_OPEN{base}'
            entry['_is_open'] = True
            entry['_openwrt_base'] = base

        if stage == 'TESTING':
            stage = 'BETA'

        if model_code not in models:
            models[model_code] = {}

        # Check if this entry is newer or the first one we see for this stage
        current_stored = models[model_code].get(stage)
        is_newer = False
        if not current_stored or entry.get('release_time', '') > current_stored.get('release_time', ''):
            is_newer = True
        
        if is_newer:
            # Validate the link before storing it
            download_link = "#"
            if 'download' in entry and entry['download']:
                 download_link = entry['download'][0].get('link', '#')
            
            print(f"[{idx+1}/{total_entries}] Validating link for {model_code} ({stage})...", end="\r")
            if check_link(download_link):
                selected_entry = dict(entry)
                selected_entry['changelog'] = changelog_to_plain_text(extract_changelog(entry))
                models[model_code][stage] = selected_entry
            else:
                # If the newer one is broken, keep the old one if it exists and was valid
                # Or just don't store it. For now, we only store if valid.
                pass

    print(f"\nProcessing complete.")
    return models

# ---------------------------------------------------------------------------
# Shared rendering helpers
# ---------------------------------------------------------------------------

def api_stage_name(stage):
    """Map an internal stage key to its lowercase API path segment (BETA_OPEN24 -> beta-open24)."""
    return stage.lower().replace('_open', '-open')

def base_stage(stage):
    """Stage name used for labels and colors (BETA_OPEN24 -> BETA)."""
    return 'BETA' if stage.startswith('BETA_OPEN') else stage

def stage_label(stage, entry=None):
    """Human readable plain-text stage label, e.g. 'BETA (OP24)' for open variants."""
    if stage.startswith('BETA_OPEN'):
        base = (entry or {}).get('_openwrt_base') or stage[len('BETA_OPEN'):] or '24'
        return f'BETA (OP{base})'
    return stage

def ordered_stages(model_stages):
    """Order a model's stage keys for display: known stages first, unknown ones
    alphabetically, and OpenWrt open variants directly after BETA (they are
    rendered in the BETA column of the overview as well)."""
    regular = [s for s in model_stages if not s.startswith('BETA_OPEN')]
    open_variants = sorted(s for s in model_stages if s.startswith('BETA_OPEN'))
    ordered = [s for s in STAGE_ORDER if s in regular] + sorted(s for s in regular if s not in STAGE_ORDER)
    insert_at = ordered.index('BETA') + 1 if 'BETA' in ordered else len(ordered)
    return ordered[:insert_at] + open_variants + ordered[insert_at:]

def entry_download_link(entry):
    """Return the first download link of a firmware entry, or '#' if none."""
    downloads = entry.get('download') or []
    if downloads:
        return downloads[0].get('link') or '#'
    return '#'

def open_badge_html(entry):
    """Small 'OP24'/'OP25' badge for OpenWrt open variants, empty string otherwise."""
    if not entry.get('_is_open'):
        return ''
    base = entry.get('_openwrt_base', '24')
    return f'<span class="badge bg-secondary ms-1" style="font-size:0.6rem;vertical-align:middle;" title="OpenWrt {base} open variant">OP{base}</span>'

def device_page_url(code):
    """Site-relative URL of a model's device page ('mt3000/'), or None if the
    model code would collide with a reserved root directory."""
    slug = code.lower()
    if slug in RESERVED_ROOT_NAMES:
        return None
    return f"{slug}/"

def html_head(title, description='', canonical=''):
    """Shared <head> (Bootstrap, Font Awesome, common styles, basic Open Graph tags)."""
    esc_title = html_lib.escape(title, quote=True)
    extra = ''
    if description:
        esc_desc = html_lib.escape(description, quote=True)
        extra += f'\n    <meta name="description" content="{esc_desc}">'
        extra += f'\n    <meta property="og:description" content="{esc_desc}">'
    if canonical:
        extra += f'\n    <link rel="canonical" href="{canonical}">'
        extra += f'\n    <meta property="og:url" content="{canonical}">'
    return f"""<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{esc_title}</title>
    <meta property="og:title" content="{esc_title}">
    <meta property="og:type" content="website">{extra}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>{PAGE_STYLE}    </style>
</head>"""

def page_footer(root=''):
    """Shared footer; `root` is the relative path back to the site root."""
    back_link = f'<p class="mb-2"><a href="{root}" class="text-decoration-none"><i class="fas fa-arrow-left me-1"></i> Back to the firmware overview</a></p>' if root else ''
    return f"""
    <footer>
        <div class="row justify-content-center">
            <div class="col-md-8">
                {back_link}
                <p class="mb-0 mt-3 small">Data is automatically verified and updated daily from GL.iNet Firmware API.</p>
            </div>
        </div>
    </footer>"""

# ---------------------------------------------------------------------------
# Overview page (index.html)
# ---------------------------------------------------------------------------

def generate_html(models, models_metadata, generated_at=None):
    generated_at = generated_at or datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')

    # Group models by type
    grouped_models = {'ROUTER': [], 'IOT': [], 'KVM': []}
    for code in models.keys():
        meta = models_metadata.get(code, {})
        m_type = meta.get('type', 'ROUTER')
        if m_type not in grouped_models:
            grouped_models[m_type] = []
        grouped_models[m_type].append(code)

    # Sort within each group
    def get_sort_key(code):
        meta = models_metadata.get(code, {})
        return meta.get('name', code)

    for m_type in grouped_models:
        grouped_models[m_type].sort(key=get_sort_key)
    
    # Collect all unique stages to create table headers, exclude internal BETA_OPEN* variants
    all_stages = set()
    for model in models:
        all_stages.update(s for s in models[model].keys() if not s.startswith('BETA_OPEN'))
    
    # Define a preferred order for columns
    sorted_stages = [s for s in STAGE_ORDER if s in all_stages] + [s for s in sorted(all_stages) if s not in STAGE_ORDER]

    head = html_head(
        "GL.iNet Firmware Overview",
        description="Latest verified GL.iNet firmware versions for all routers, IoT and KVM devices, with a flat-file API.",
        canonical=f"{SITE_URL}/",
    )

    html = f"""
<!DOCTYPE html>
<html lang="en">
{head}
<body>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 text-center mb-4">
            <h1><i class="fas fa-microchip text-primary"></i> GL.iNet Firmware Overview</h1>
            <p class="lead">Latest verified firmware versions</p>
            <div class="mb-2">
                <span class="badge bg-info text-dark">Community Project by <a href="https://admon.me" target="_blank" class="text-dark text-decoration-none fw-bold">admon (admon.me)</a></span>
            </div>
            <p class="timestamp">Last updated: {generated_at}</p>
        </div>
    </div>

    <div class="row justify-content-center search-container">
        <div class="col-md-8">
            <div class="input-group">
                <span class="input-group-text bg-white"><i class="fas fa-search text-muted"></i></span>
                <input type="text" id="searchInput" class="form-control form-control-lg border-start-0" placeholder="Search for model (e.g. AX1800) or code (e.g. flint)...">
            </div>
        </div>
    </div>

    <div class="row justify-content-center mb-4">
        <div class="col-md-10">
            <div class="accordion shadow-sm" id="apiAccordion">
                <div class="accordion-item border-0">
                    <h2 class="accordion-header" id="headingAPI">
                        <button class="accordion-button collapsed fw-bold bg-white text-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAPI" aria-expanded="false" aria-controls="collapseAPI">
                            <i class="fas fa-code me-2"></i> How to use the Flat-File API
                        </button>
                    </h2>
                    <div id="collapseAPI" class="accordion-collapse collapse" aria-labelledby="headingAPI" data-bs-parent="#apiAccordion">
                        <div class="accordion-body api-info m-0 border-top">
                            <p class="small mb-2">
                                This dashboard provides a machine-readable flat-file API. You can access firmware information directly:
                            </p>
                            <ul class="small mb-0">
                                <li><strong>Available stages:</strong> <code>/api/&lt;model&gt;/branches</code> (e.g., <code>/api/ax1800/branches</code>)</li>
                                <li><strong>Version string:</strong> <code>/api/&lt;model&gt;/&lt;stage&gt;/version</code> (e.g., <code>/api/ax1800/release/version</code>)</li>
                                <li><strong>Download URL:</strong> <code>/api/&lt;model&gt;/&lt;stage&gt;/url</code></li>
                                <li><strong>Latest changelog:</strong> <code>/api/&lt;model&gt;/&lt;stage&gt;/changelog</code></li>
                                <li><strong>Specific attributes:</strong> <code>/api/&lt;model&gt;/&lt;stage&gt;/[version|url|date|hash|changelog]</code></li>
                                <li><strong>Consolidated data:</strong> <code>/api/all.json</code></li>
                                <li><strong>Device page (deep link):</strong> <code>/&lt;model&gt;/</code> (e.g., <a href="{device_page_url('ax1800')}"><code>/ax1800/</code></a>) &ndash; click a model name below</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    """

    for m_type in ['ROUTER', 'IOT', 'KVM']:
        codes = grouped_models.get(m_type, [])
        if not codes:
            continue
            
        icon = TYPE_ICONS.get(m_type, 'fa-device')
        name = TYPE_NAMES.get(m_type, m_type)

        html += f"""
    <h3 class="section-title" id="{m_type.lower()}"><i class="fas {icon} text-primary"></i> {name}</h3>
    <div class="card mb-5">
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover table-striped mb-0 firmware-table">
                    <thead class="table-dark">
                        <tr>
                            <th scope="col" class="ps-4" style="min-width: 200px;">Model</th>
                            {''.join([f'<th scope="col">{s}</th>' for s in sorted_stages])}
                        </tr>
                    </thead>
                    <tbody>
        """

        for code in codes:
            meta = models_metadata.get(code, {})
            full_name = html_lib.escape(meta.get('name', code))
            page_url = device_page_url(code)
            name_html = f'<a href="{page_url}" class="model-link" title="Open device page for {full_name}">{full_name} <i class="fas fa-link ms-1"></i></a>' if page_url else full_name
            
            html += f"""
            <tr id="{code.lower()}">
                <td class='ps-4'>
                    <div class="fw-bold">{name_html}</div>
                    <div class="text-muted small" style="font-size: 0.7rem;">{html_lib.escape(code)}</div>
                </td>
            """
            for stage in sorted_stages:
                info = models[code].get(stage)
                # Gather all OpenWrt "open" variants (op24, op25, ...) alongside the BETA column
                open_stages = sorted(s for s in models[code] if s.startswith('BETA_OPEN')) if stage == 'BETA' else []
                # (actual_stage, entry) pairs to render in this cell
                render_list = [(stage, info)] if info else []
                render_list += [(s, models[code][s]) for s in open_stages]
                if render_list:
                    cells = []
                    for entry_stage, entry_info in render_list:
                        version = entry_info.get('version', 'N/A')
                        release_time = entry_info.get('release_time', '').split(' ')[0]
                        download_link = entry_download_link(entry_info)
                        changelog_text = (entry_info.get('changelog') or '').strip()
                        timestamp_html = f'<span class="timestamp">{release_time}</span>'
                        if changelog_text:
                            changelog_path = f"api/{code.lower()}/{api_stage_name(entry_stage)}/changelog"
                            timestamp_html = f'<a class="timestamp text-decoration-none" href="{changelog_path}" target="_blank" title="Open latest changelog TXT">{release_time} <i class="fas fa-file-lines small ms-1"></i></a>'
                        open_badge = open_badge_html(entry_info)
                        cells.append(f'''
                                <div class="d-flex flex-column{'  border-top pt-1 mt-1' if entry_info.get('_is_open') and info else ''}">
                                    <a href="{download_link}" target="_blank" class="fw-version text-decoration-none stage-{stage}">
                                        {version} <i class="fas fa-download small ms-1"></i>
                                    </a>
                                    <div>{timestamp_html}{open_badge}</div>
                                </div>''')
                    html += f"<td>{''.join(cells)}</td>"
                else:
                    html += "<td><span class='text-muted'>-</span></td>"
            html += "</tr>"

        html += """
                    </tbody>
                </table>
            </div>
        </div>
    </div>
        """

    html += page_footer()

    html += """
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
    document.getElementById('searchInput').addEventListener('keyup', function() {
        var input = this.value.toLowerCase();
        var tables = document.querySelectorAll('.firmware-table');
        
        tables.forEach(function(table) {
            var rows = table.querySelectorAll('tbody tr');
            var visibleRows = 0;
            
            rows.forEach(function(row) {
                var text = row.textContent.toLowerCase();
                if (text.includes(input)) {
                    row.style.display = '';
                    visibleRows++;
                } else {
                    row.style.display = 'none';
                }
            });
            
            // Hide the entire table section if no rows are visible
            var card = table.closest('.card');
            var title = card.previousElementSibling;
            if (visibleRows === 0) {
                card.style.display = 'none';
                if (title && title.classList.contains('section-title')) {
                    title.style.display = 'none';
                }
            } else {
                card.style.display = '';
                if (title && title.classList.contains('section-title')) {
                    title.style.display = '';
                }
            }
        });
    });
</script>

</body>
</html>
    """
    return html

# ---------------------------------------------------------------------------
# Device pages (<model>/index.html at the site root)
# ---------------------------------------------------------------------------

def generate_device_page(code, stages, meta, generated_at):
    """Build the standalone HTML page of a single model, served at /<model>/."""
    code_lower = code.lower()
    full_name = meta.get('name', code)
    m_type = meta.get('type', 'ROUTER')
    icon = TYPE_ICONS.get(m_type, 'fa-microchip')
    type_name = TYPE_NAMES.get(m_type, m_type)
    esc_name = html_lib.escape(full_name)
    esc_code = html_lib.escape(code)
    canonical = f"{SITE_URL}/{device_page_url(code)}"
    # Device pages live one directory level below the site root
    root = '../'
    api_rel = f"{root}api/{code_lower}"
    api_abs = f"{SITE_URL}/api/{code_lower}"

    display_stages = ordered_stages(stages)

    summary_parts = []
    rows = []
    changelog_blocks = []
    endpoint_items = []
    for stage in display_stages:
        info = stages[stage]
        s_api = api_stage_name(stage)
        label = base_stage(stage)
        version = info.get('version', 'N/A')
        esc_version = html_lib.escape(version)
        release_time = info.get('release_time', '')
        release_date = release_time.split(' ')[0]
        download_link = entry_download_link(info)
        md5_hash = (info.get('download') or [{}])[0].get('md5', '') or ''
        changelog_text = (info.get('changelog') or '').strip()
        badge = open_badge_html(info)

        summary_parts.append(f"{stage_label(stage, info)} {version}")

        hash_html = f'<div class="timestamp font-monospace" title="MD5">MD5 {html_lib.escape(md5_hash)}</div>' if md5_hash else ''
        if changelog_text:
            changelog_cell = f'<a href="#changelog-{s_api}" class="text-decoration-none" title="Jump to changelog"><i class="fas fa-file-lines me-1"></i>Changelog</a>'
            changelog_blocks.append(f"""
                <details id="changelog-{s_api}" class="mb-3"{' open' if not changelog_blocks else ''}>
                    <summary class="fw-bold"><span class="stage-{label}">{label}</span>{badge} <span class="fw-version">{esc_version}</span> <span class="timestamp ms-1">{html_lib.escape(release_date)}</span>
                        <a href="{api_rel}/{s_api}/changelog" target="_blank" class="small text-decoration-none ms-2" title="Open as plain text">TXT <i class="fas fa-arrow-up-right-from-square small"></i></a></summary>
                    <pre class="changelog-text mt-2">{html_lib.escape(changelog_text)}</pre>
                </details>""")
        else:
            changelog_cell = '<span class="text-muted">-</span>'

        rows.append(f"""
                        <tr id="{s_api}">
                            <td class="ps-4"><span class="fw-bold stage-{label}">{label}</span>{badge}</td>
                            <td><span class="fw-version">{esc_version}</span>{hash_html}</td>
                            <td class="text-nowrap"><span class="timestamp" title="{html_lib.escape(release_time, quote=True)}">{html_lib.escape(release_date)}</span></td>
                            <td><a href="{download_link}" target="_blank" class="btn btn-sm btn-outline-primary text-nowrap"><i class="fas fa-download me-1"></i>Download</a></td>
                            <td>{changelog_cell}</td>
                        </tr>""")

        attr_links = ' &middot; '.join(
            f'<a href="{api_rel}/{s_api}/{attr}" target="_blank">{attr}</a>'
            for attr in ['version', 'url', 'date', 'hash', 'changelog']
        )
        endpoint_items.append(f'<li class="mb-1"><strong>{label}{badge}:</strong> <code>{api_abs}/{s_api}/</code> <span class="ms-1">[ {attr_links} ]</span></li>')

    if rows:
        firmware_section = f"""
    <h3 class="section-title"><i class="fas fa-download text-primary"></i> Firmware versions</h3>
    <div class="card">
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover table-striped mb-0 align-middle">
                    <thead class="table-dark">
                        <tr>
                            <th scope="col" class="ps-4">Stage</th>
                            <th scope="col">Version</th>
                            <th scope="col">Released</th>
                            <th scope="col">Download</th>
                            <th scope="col">Changelog</th>
                        </tr>
                    </thead>
                    <tbody>{''.join(rows)}
                    </tbody>
                </table>
            </div>
        </div>
    </div>"""
        example_stage = api_stage_name(display_stages[0])
    else:
        firmware_section = """
    <div class="alert alert-warning shadow-sm" role="alert">
        <i class="fas fa-triangle-exclamation me-2"></i> No verified firmware download is currently available for this model.
    </div>"""
        example_stage = 'release'

    changelog_section = ''
    if changelog_blocks:
        changelog_section = f"""
    <h3 class="section-title"><i class="fas fa-file-lines text-primary"></i> Changelogs</h3>
    <div class="card">
        <div class="card-body">{''.join(changelog_blocks)}
        </div>
    </div>"""

    description = f"Latest verified GL.iNet firmware for {full_name} ({code})"
    if summary_parts:
        description += ": " + ", ".join(summary_parts)
    description += "."

    head = html_head(f"{full_name} Firmware | GL.iNet Firmware Overview", description=description, canonical=canonical)

    return f"""<!DOCTYPE html>
{DEVICE_PAGE_MARKER}
<html lang="en">
{head}
<body>

<div class="container">
    <nav aria-label="breadcrumb" class="mb-3">
        <ol class="breadcrumb small mb-0">
            <li class="breadcrumb-item"><a href="{root}" class="text-decoration-none"><i class="fas fa-microchip me-1"></i>GL.iNet Firmware Overview</a></li>
            <li class="breadcrumb-item"><a href="{root}#{m_type.lower()}" class="text-decoration-none">{html_lib.escape(type_name)}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{esc_name}</li>
        </ol>
    </nav>

    <div class="row justify-content-center">
        <div class="col-12 text-center mb-4">
            <h1><i class="fas {icon} text-primary"></i> {esc_name}</h1>
            <p class="lead mb-2">Latest verified firmware versions</p>
            <div class="mb-2">
                <span class="badge bg-dark font-monospace">{esc_code}</span>
                <span class="badge bg-secondary">{html_lib.escape(type_name)}</span>
            </div>
            <p class="timestamp mb-1">Last updated: {generated_at}</p>
            <p class="timestamp">Permalink: <a href="{canonical}" class="text-decoration-none font-monospace">{canonical}</a></p>
        </div>
    </div>
{firmware_section}
{changelog_section}
    <h3 class="section-title"><i class="fas fa-code text-primary"></i> API endpoints for this device</h3>
    <div class="card">
        <div class="card-body api-info m-0">
            <ul class="small mb-2">
                <li class="mb-1"><strong>Available stages:</strong> <code>{api_abs}/branches</code> <span class="ms-1">[ <a href="{api_rel}/branches" target="_blank">open</a> ]</span></li>
                {''.join(endpoint_items)}
            </ul>
            <p class="small mb-0"><strong>Example:</strong> <code>curl -s {api_abs}/{example_stage}/version</code></p>
        </div>
    </div>
{page_footer(root)}
</div>

</body>
</html>
"""

def remove_stale_device_pages():
    """Delete root-level directories that hold a device page from a previous run.
    Only directories whose index.html carries DEVICE_PAGE_MARKER are touched."""
    for name in os.listdir('.'):
        page = os.path.join(name, 'index.html')
        if name in RESERVED_ROOT_NAMES or not os.path.isdir(name) or not os.path.isfile(page):
            continue
        with open(page, encoding='utf-8', errors='ignore') as f:
            if DEVICE_PAGE_MARKER in f.read(2048):
                shutil.rmtree(name)

def generate_device_pages(models, models_metadata, generated_at):
    """Write one standalone HTML page per model to <model>/index.html at the site
    root. Returns the number of pages written."""
    remove_stale_device_pages()

    written = 0
    for code, stages in models.items():
        page_url = device_page_url(code)
        if page_url is None:
            print(f"Skipping device page for '{code}': it would collide with a reserved directory.")
            continue
        meta = models_metadata.get(code, {})
        page_dir = code.lower()
        os.makedirs(page_dir, exist_ok=True)
        with open(os.path.join(page_dir, 'index.html'), 'w', encoding='utf-8') as f:
            f.write(generate_device_page(code, stages, meta, generated_at))
        written += 1
    return written

# ---------------------------------------------------------------------------
# Flat-file API (api/...)
# ---------------------------------------------------------------------------

def generate_api_files(models):
    api_dir = 'api'
    if os.path.exists(api_dir):
        shutil.rmtree(api_dir)
    os.makedirs(api_dir)
    
    # Also generate a consolidated JSON
    all_data = {}

    for model_code, stages in models.items():
        model_code_lower = model_code.lower()
        model_dir = os.path.join(api_dir, model_code_lower)
        if not os.path.exists(model_dir):
            os.makedirs(model_dir)
        
        # List available branches/stages for this model
        available_stages = sorted([api_stage_name(s) for s in stages.keys()])
        branches_content = '\n'.join(available_stages) + '\n'
        
        # 1. Provide at api/model_code/branches
        with open(os.path.join(model_dir, 'branches'), 'w') as f:
            f.write(branches_content)
            
        # 2. Provide at api/model_code/index.html (served as /api/model_code/)
        with open(os.path.join(model_dir, 'index.html'), 'w') as f:
            f.write(branches_content)
            
        all_data[model_code_lower] = {}
        
        for stage, info in stages.items():
            s_name = api_stage_name(stage)
            version = info.get('version', 'N/A')
            release_time = info.get('release_time', '')
            download_url = info.get('download', [{}])[0].get('link', '')
            # Try to find a hash (md5 is common in GL.iNet API)
            md5_hash = info.get('download', [{}])[0].get('md5', '')
            changelog = (info.get('changelog') or '').strip()
            changelog_path = f"{SITE_URL}/api/{model_code_lower}/{s_name}/changelog"
            
            summary_content = f"version: {version}\nhash: {md5_hash}\ndownload: {download_url}\ndate: {release_time}\nchangelog: {changelog_path}\n"
            
            all_data[model_code_lower][s_name] = {
                'version': version,
                'release_time': release_time,
                'download': download_url,
                'md5': md5_hash,
                'changelog': changelog_path
            }
            
            # Simple structure: api/model/stage/attribute
            stage_path = os.path.join(model_dir, s_name)
            
            # If a file exists where we want a directory, remove it
            if os.path.exists(stage_path) and not os.path.isdir(stage_path):
                os.remove(stage_path)
            
            if not os.path.exists(stage_path):
                os.makedirs(stage_path)
            
            # Summary file at the stage directory level
            with open(os.path.join(stage_path, 'index.html'), 'w') as f:
                f.write(summary_content)
            
            # Sub-files for specific attributes
            with open(os.path.join(stage_path, 'version'), 'w') as f:
                f.write(version + '\n')
            with open(os.path.join(stage_path, 'url'), 'w') as f:
                f.write(download_url + '\n')
            with open(os.path.join(stage_path, 'date'), 'w') as f:
                f.write(release_time + '\n')
            with open(os.path.join(stage_path, 'hash'), 'w') as f:
                f.write(md5_hash + '\n')
            with open(os.path.join(stage_path, 'changelog'), 'w', encoding='utf-8') as f:
                f.write(changelog + '\n')

    with open(os.path.join(api_dir, 'all.json'), 'w', encoding='utf-8') as f:
        json.dump(all_data, f, indent=2, ensure_ascii=False)

def main():
    print("Loading models metadata...")
    models_metadata = {}
    if os.path.exists('models.json'):
        with open('models.json', 'r') as f:
            models_metadata = json.load(f)
    
    if not models_metadata:
        print("No models metadata found. Please run fetch_all_models.py first.")
        exit(1)

    print(f"Fetching firmware data for {len(models_metadata)} models...")
    raw_data = fetch_data_individual(models_metadata.keys())
    
    if raw_data and raw_data.get('info'):
        print(f"Data fetched. Processing {len(raw_data['info'])} entries...")
        models = process_data(raw_data, models_metadata)
        generated_at = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
        
        print("Generating API files...")
        generate_api_files(models)

        print(f"Generating device pages for {len(models)} models...")
        pages_written = generate_device_pages(models, models_metadata, generated_at)
        
        print(f"Generating HTML for {len(models)} models...")
        html_content = generate_html(models, models_metadata, generated_at)
        
        with open('index.html', 'w', encoding='utf-8') as f:
            f.write(html_content)
        print(f"Done. index.html, api/ files and {pages_written} device pages created.")
    else:
        print("Failed to fetch or process data.")
        exit(1)



if __name__ == "__main__":
    main()
