"""Shared constants and pure helpers used by the fetcher and every renderer.

This module is part of the phase contract: renderers import from here and never
re-implement these helpers.
"""
import html as html_lib
import os
import re
from datetime import date, datetime, timedelta

# Public base URL of the deployed site (absolute links in API files, device pages and link previews)
SITE_URL = "https://firmware.gl-i.net"

SITE_NAME = "GL.iNet Firmware Overview"

# Preview image for links shared on social media / forums (Open Graph, Twitter Card)
OG_IMAGE_PATH = 'images/og-image.png'

OG_IMAGE_SIZE = (1200, 630)


# Per-model pages are generated at the site root (/<model>/index.html). Root entries
# that a model page must never overwrite:
RESERVED_ROOT_NAMES = {'api', 'images', 'cloudflare', '.git', '.github', '.claude',
                       'all', 'cli', 'routers', 'iot', 'kvm', 'docs', 'new', 'sitelib', 'tests'}

# Marker embedded in generated model pages so stale ones can be removed safely
DEVICE_PAGE_MARKER = '<!-- generated by generate_page.py (device page) -->'

# Preferred order of firmware stages; unknown stages follow alphabetically
STAGE_ORDER = ['RELEASE', 'BETA', 'SNAPSHOT', 'RC']


TYPE_NAMES = {
    'ROUTER': 'Routers',
    'IOT': 'IoT Devices',
    'KVM': 'KVM / Comet Series'
}

# URL slug of the per-category text pages (/routers, /iot, /kvm)
TYPE_SLUGS = {'ROUTER': 'routers', 'IOT': 'iot', 'KVM': 'kvm'}


# Seconds a firmware download link gets to answer a single HEAD request. A
# healthy answer takes well under a second, so this is generous on purpose.
LINK_TIMEOUT = 8

# Transient failures (timeout, reset, 5xx, 429) are retried; a 404 is not.
LINK_ATTEMPTS = 3

LINK_BACKOFF = (1, 3)  # seconds to wait before attempt 2 and attempt 3

# Upper bound on the extra time retries may cost across one whole run, so a bad
# day upstream cannot turn a 90 second build into an hour of waiting. Once it is
# used up the remaining links get a single attempt each.
RETRY_BUDGET = 180

# When the newest build's download is unreachable, how many older builds to
# probe for one that still downloads. Those probes get a single attempt each so
# one broken model cannot eat the whole retry budget.
FALLBACK_CANDIDATES = 5

def entry_link(entry):
    if entry.get('download'):
        return entry['download'][0].get('link', '') or ''
    return ''

def api_stage_name(stage):
    """Map an internal stage key to its lowercase API path segment (BETA_OPEN24 -> beta-open24)."""
    return stage.lower().replace('_open', '-open')


def stage_label(stage, entry=None):
    """Human readable plain-text stage label, e.g. 'BETA (OP24)' for open variants."""
    if stage.startswith('BETA_OPEN'):
        base = (entry or {}).get('_openwrt_base') or stage[len('BETA_OPEN'):] or '24'
        return f'BETA (OP{base})'
    return stage

def ordered_stages(model_stages):
    """Order a model's stage keys for display: known stages first, unknown ones
    alphabetically, and OpenWrt open variants directly after BETA (they are
    rendered in the BETA column of the overview as well)."""
    regular = [s for s in model_stages if not s.startswith('BETA_OPEN')]
    open_variants = sorted(s for s in model_stages if s.startswith('BETA_OPEN'))
    ordered = [s for s in STAGE_ORDER if s in regular] + sorted(s for s in regular if s not in STAGE_ORDER)
    insert_at = ordered.index('BETA') + 1 if 'BETA' in ordered else len(ordered)
    return ordered[:insert_at] + open_variants + ordered[insert_at:]


def group_models_by_type(models, models_metadata):
    """Model codes grouped by device type (ROUTER/IOT/KVM), sorted by display name."""
    grouped = {'ROUTER': [], 'IOT': [], 'KVM': []}
    for code in models:
        m_type = models_metadata.get(code, {}).get('type', 'ROUTER')
        grouped.setdefault(m_type, []).append(code)
    for codes in grouped.values():
        codes.sort(key=lambda c: models_metadata.get(c, {}).get('name', c))
    return grouped

def overview_stage_columns(models):
    """Stage columns of the overview: known stages first, the rest alphabetically,
    OpenWrt open variants excluded (they are shown inside the BETA column)."""
    all_stages = set()
    for stages in models.values():
        all_stages.update(s for s in stages if not s.startswith('BETA_OPEN'))
    return [s for s in STAGE_ORDER if s in all_stages] + [s for s in sorted(all_stages) if s not in STAGE_ORDER]

def device_page_url(code):
    """Site-relative URL of a model's device page ('mt3000/'), or None if the
    model code would collide with a reserved root directory."""
    slug = code.lower()
    if slug in RESERVED_ROOT_NAMES:
        return None
    return f"{slug}/"


# ---------------------------------------------------------------------------
# Phase "Redesign" contract: links, age, recent builds, feeds, display names.
# Every renderer uses these helpers instead of reading release_time or names itself.
# ---------------------------------------------------------------------------

GITHUB_URL = "https://github.com/admonstrator/glinet-firmware-overview"
SPONSOR_URL = "https://github.com/sponsors/admonstrator"
AUTHOR_URL = "https://admon.me"
FORUM_URL = "https://forum.gl-inet.com/"

DOCS_DIR = 'docs'          # /docs/  API & terminal documentation (HTML + index.txt)
NEW_DIR = 'new'            # /new    recently released builds as text for curl
FEED_FILE = 'feed.xml'     # /feed.xml and /<model>/feed.xml (Atom 1.0)

FRESH_DAYS = 14            # "new" tag next to a version
RECENT_DAYS = 14           # "Recently released" section, /new and the global feed window
RECENT_EXCLUDED_STAGES = frozenset({'SNAPSHOT'})   # too frequent for "recent" and the global feed
GLOBAL_FEED_LIMIT = 50     # newest builds in /feed.xml

def parse_generated_at(generated_at):
    """'2026-09-26 13:23:07 UTC' -> naive datetime; falls back to now() for anything else."""
    try:
        return datetime.strptime((generated_at or '').replace(' UTC', '').strip(), '%Y-%m-%d %H:%M:%S')
    except ValueError:
        return datetime.now()

def build_date(entry):
    """Release date of a firmware entry as a date, or None when the API gave none."""
    try:
        return datetime.strptime((entry.get('release_time') or '')[:10], '%Y-%m-%d').date()
    except ValueError:
        return None

def days_since(entry, now):
    """Whole days between the entry's release date and `now` (a datetime), or None."""
    d = build_date(entry)
    return None if d is None else max(0, (now.date() - d).days)

def age_text(days):
    """Relative age for prose: 'today', 'yesterday', '5 days ago', '3 weeks ago', '4 months ago', '2 years ago'."""
    if days is None:
        return 'unknown'
    if days == 0:
        return 'today'
    if days == 1:
        return 'yesterday'
    if days < 14:
        return f'{days} days ago'
    if days < 60:
        return f'{days // 7} weeks ago'
    if days < 730:
        return f'{days // 30} months ago'
    return f'{days // 365} years ago'

def age_short(days):
    """Compact relative age for tables: '0d', '5d', '3w', '4mo', '2y' ('-' when unknown)."""
    if days is None:
        return '-'
    if days < 14:
        return f'{days}d'
    if days < 60:
        return f'{days // 7}w'
    if days < 730:
        return f'{days // 30}mo'
    return f'{days // 365}y'

def is_fresh(entry, now):
    """True when the build is at most FRESH_DAYS old."""
    d = days_since(entry, now)
    return d is not None and d <= FRESH_DAYS

def latest_update(stages):
    """(stage, entry) of the newest build across all stages of one device, or (None, None)."""
    best = (None, None)
    for stage, entry in stages.items():
        if best[1] is None or (entry.get('release_time') or '') > (best[1].get('release_time') or ''):
            best = (stage, entry)
    return best

def builds_newest_first(models, models_metadata, exclude=frozenset()):
    """Every build as a dict {code, name, type, stage, entry}, newest first (ties by code, stage)."""
    items = []
    for code, stages in models.items():
        meta = models_metadata.get(code, {})
        for stage, entry in stages.items():
            if stage in exclude:
                continue
            items.append({'code': code, 'name': meta.get('name', code), 'type': meta.get('type', 'ROUTER'),
                          'stage': stage, 'entry': entry})
    items.sort(key=lambda b: (b['code'].lower(), b['stage']))
    items.sort(key=lambda b: b['entry'].get('release_time') or '', reverse=True)
    return items

def recent_builds(models, models_metadata, now, days=RECENT_DAYS, exclude=RECENT_EXCLUDED_STAGES):
    """Builds released within `days` of `now`, newest first; each dict also carries 'days'.
    This is the single definition behind the overview section, /new and the global feed window."""
    out = []
    for b in builds_newest_first(models, models_metadata, exclude):
        d = days_since(b['entry'], now)
        if d is not None and d <= days:
            out.append(dict(b, days=d))
    return out

def feed_url(code=None, absolute=False, root=''):
    """URL of the global feed (code=None) or a device feed. Relative to the site root
    (prefix `root`, e.g. '../') unless absolute=True."""
    path = FEED_FILE if code is None else f'{code.lower()}/{FEED_FILE}'
    return f'{SITE_URL}/{path}' if absolute else f'{root}{path}'

def feed_entry_id(code, stage, version):
    """Stable Atom entry id for one build."""
    return f'tag:firmware.gl-i.net,2026:{code.lower()}/{api_stage_name(stage)}/{version}'

def split_name(name, code):
    """Split 'GL-MT3000 Beryl AX' into ('Beryl AX', 'GL-MT3000'). Names without a nickname stay
    whole; the second part then is the API code, or '' when the name already contains it."""
    parts = (name or code).split(' ', 1)
    if len(parts) == 2 and parts[0].upper().startswith(('GL-', 'MICROUTER')) and not parts[1].startswith('('):
        return parts[1], parts[0]
    full = name or code
    return full, ('' if code.upper() in full.upper() else code.upper())

def stage_class(stage):
    """CSS colour class of a stage: release, beta, snapshot, rc or other (clean, legacy, tor, ...).
    OpenWrt open variants (BETA_OPENxx) are beta."""
    s = stage.upper()
    if s.startswith('BETA_OPEN'):
        return 'beta'
    return s.lower() if s in ('RELEASE', 'BETA', 'SNAPSHOT', 'RC') else 'other'

def stage_title(stage, entry=None):
    """Human stage name for the new design: 'Release', 'Beta', 'Beta OP24', 'Clean', ..."""
    s = stage.upper()
    if s.startswith('BETA_OPEN'):
        base = (entry or {}).get('_openwrt_base') or s[len('BETA_OPEN'):] or '24'
        return f'Beta OP{base}'
    return s.capitalize()
